### ISSUE TITLE
Keep helmsman from creating namespace

### ISSUE THREAD

**Issue by bobhenkel** [Praqma/helmsman#100]
In our current setup we have a helm chart that creates namespaces to our platform teams spec that dev teams can use, it setups some namespace roles, resource quotas, and service account for the namespace to name a few. We put a super tiller/root tiller/god tiller whatever you want to call it in a tools namespace that the platform team creates on cluster creation.  Once that tiller is up we can install our helm chart namespace-creator to create new namespaces and install a tiller into the namespace being created so that the team that owns the namespace is tiller scoped to their namespace. With helmsman I'm running into the issue that it wants to create the namespace as soon as I mention it and if it doesn't exists, and in our case we don't want helmsman to manage our namespace out of band(not a helm chart install). Take this example toml.

```
[namespaces]
  [namespaces.bob-helmsman]
    protected = false
    useTiller = false
  [namespaces.kube-system]
    protected = true
    installTiller = false
  [namespaces.tools]
    protected = true
    useTiller = true

[helmRepos]
  stable = "https://kubernetes-charts.storage.googleapis.com"
  bob-repo =  "http://127.0.0.1:8080"


[apps]

  [apps.namespace-creator]
    namespace = "bob-helmsman" # maps to the namespace as defined in namespaces above
    enabled = true # change to false if you want to delete this app release [default = false]
    chart = "bob/namespace-creator" # changing the chart name means delete and recreate this release
    version = "0.1.9" # chart version
    ### Optional values below
    name = "namespace-creator" # should be unique across all apps which are managed by the same Tiller
    valuesFile = "" # leaving it empty uses the default chart values
    tillerNamespace = "tools" # which Tiller to use to deploy this release
    purge = true # will only be considered when there is a delete operation
    test = false # run the tests when this release is installed for the first time only
    protected = false
    priority= -100
    [apps.namespace-creator.set]
      "namespaceQuota.enabled" = "true"
      "namespaceQuota.requestsCpu" = "400m"
      "namespaceQuota.requestsMemory" = "1Gi"
      "namespaceQuota.limitsCpu" = "500m"
      "namespaceQuota.limitsMemory" = "1Gi"
      "podLimit.pods" = "100"
      "labels.environment" = "live"
      "labels.slackchannel" = "bob"
      "labels.team" = "bob"
```

The problem is helmsman will try to create the bob-helmsman namespace before my app install can run the helm install for namespace-creator. Is there any way to tell helmsman that hey here's a namespace, but don't attempt to create it?

**Comment by bobhenkel** [comment]
Just a little more context.

In my setup a dev team owns their namespace, but our platform team approves prs that create namespaces and resource quotas for those name spaces.  Think of it as multi tenant setup our tenants are just different teams.  Once they have a namespace they can deploy what they want in their namespace so it would be nice to recommend they use helmsman except helmsman currently believes it should try to create namespaces.  The service accounts our dev teams use won’t allow them to do that even if they try.

**Comment by bobhenkel** [comment]
@luisdavim Thanks for this! So far so good. It's leaving our namespaces alone.:)

**Comment by sami-alajrami** [comment]
as of v1.7.0 namespaces won't be created without `--apply` and you can of course prevent at all times with `--no-ns`
