### ISSUE TITLE
Kube context in cluster

### ISSUE THREAD

**Issue by theallseingeye** [Praqma/helmsman#107]
How can I run this inside the cluster if I want to reuse my existing pods service account

**Comment by sami-alajrami** [comment]
@theallseingeye not sure I get your question. What do you want to run inside the cluster? and what do you want to reuse the pods service accounts for?

For deploying Tiller with existing service accounts, please check documentation [here](https://github.com/Praqma/helmsman/blob/master/docs/how_to/multitenant_clusters_guide.md#deploying-tiller-with-a-service-account)
For using a context that you have in your local kubeconfig, simply set the context name in your desired state file https://github.com/Praqma/helmsman/blob/5ea35e7a03b8f9ed0bf42567b0cc0c87eb5db622/example.yaml#L17
Hope this helps. If not, please provide more context about what you want to achieve.

**Comment by theallseingeye** [comment]
When you run kubectl from inside a pod, it can pick up the serviceaccount which the pod has access  to and the context without a ~/.kube/config can we do something like that with helmsman (or I think it might be helm) 

Ie. /var/run/secrets/kubernetes.io/ serviceaccount

**Comment by sami-alajrami** [comment]
you can do this in your helm chart. 
Helmsman only deals with deploying your charts in your cluster and usually sets outside the cluster (e.g. in a docker container in your CI/CD platform or on your machine).

**Comment by theallseingeye** [comment]
My ci/cd was running inside kubernetes, turns out I needed to create my kubeconfig first with something like this, would be useful if I can define this in helmsman context generation itself

```
    - kubectl config set-cluster default --server=https://kubernetes.default --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    - kubectl config set-context default --cluster=default
    - token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
    - kubectl config set-credentials user --token=$token
    - kubectl config set-context default --user=user
    - kubectl config use-context default
```

I think I can only use username/password with helmsman generation

**Comment by erihanse** [comment]
@sami-alajrami 
We have Jenkins running within the cluster (using the kubernetes plugin). By using the service account, no context is needed. Are there any plans to support running helmsman within the cluster?

**Comment by sami-alajrami** [comment]
@erihanse running helmsman from within the cluster (using a service account to access the API) will require changing the way helmsman currently interacts with the cluster (using kubectl and helm commands over a kube context) to use API calls from client libraries instead. 

Alternatively, we can try to allow defining a context using the bearer token from the service account as described in the comments above. This (while still creates a context), will be talking to the cluster internally.
