### ISSUE TITLE
helmsman not getting an exit code

### ISSUE THREAD

**Issue by theallseingeye** [Praqma/helmsman#114]
I'm using gitlab ci but don't seem exit when it fails, 

It gives me the error message: `Command returned with exit code: . And error message: Error: UPGRADE FAILED: failed to create resource: `

Weird that the exit code is not returned properly. The CI hangs because I'm running helm serve & and doesn't take the "exit 1"

gitlab-ci.yaml snippet:

```
dev:
  stage: dev
  image: helmsman

  script:
    - |
      helm serve &
      helmsman -f infra/namespaces/staging/helmsman.yaml --apply || exit 1
      killall -9 helm; exit 0
```

**Comment by sami-alajrami** [comment]
@theallseingeye how about using `trap` like this (assuming you don't want to use a helm repo):
```
dev:
  stage: dev
  image: helmsman

  script:
    - |
      helm serve &
      trap "killall -9 helm; exit 0" EXIT
      helmsman -f infra/namespaces/staging/helmsman.yaml --apply 
```

Relying on exit code 1 as you had in your script, may not always work. As helm, helmsman, kubectl could return different codes.
