### ISSUE TITLE
Configuration fields validation

### ISSUE THREAD

**Issue by hatemosphere** [Praqma/helmsman#126]
I wonder if it's possible to add validation for unknown fields in Helmsman configs. The reasoning behind this is simple - for example, we've spent a lot of time to debug this issue - https://github.com/Praqma/helmsman/issues/105, and now with 1.7.0 our config is broken again, since field was renamed and Helmsman is not complaining about this.

**Comment by luisdavim** [comment]
maybe we can use `UnmarshalStrict` instead of `Unmarshal`, at least for the `yaml` files, I don't know if there's an equivalent method on the `Toml` library used by Helmsman.

**Comment by luisdavim** [comment]
for `Toml` files we can use this https://godoc.org/github.com/BurntSushi/toml#example-package--StrictDecoding

**Comment by luisdavim** [comment]
so this was fixed by #132 right?

**Comment by hatemosphere** [comment]
yup, closing this issue
