### ISSUE TITLE
Upgrade determinations fails with versions prefixed with 'v'

### ISSUE THREAD

**Issue by lachlancooper** [Praqma/helmsman#133]
This issue is similar to #85.

We have a chart that is always flagged as needing an upgrade, even when the chart version and values have not changed. For example:

```
DECISION: release [ cert-manager ] is desired to be upgraded. Planing this for you! – priority: 0
```

Upon examination, this chart prefixes its version with `v`, which is not supported by this regex:

https://github.com/Praqma/helmsman/blob/5ca4121f3054d72e1d415cc1df41816b19f73c31/helm_helpers.go#L192

This is one of only two `stable` charts to use `v` version prefixes, which is presumably why the issue has not been detected before now.

**Comment by luisdavim** [comment]
Hi,

can you test a build from #134 and let me know if that's enough to fix your issue?

**Comment by lachlancooper** [comment]
That change does indeed fix the issue:
```
DECISION: release [ cert-manager ] is desired to be enabled and is currently enabled. Nothing to do here! -- priority: 0
```
Thanks very much!
