### ISSUE TITLE
utils.toFile function calls incorrect parsing method to yaml extensions

### ISSUE THREAD

**Issue by shaunmansell** [Praqma/helmsman#135]
The `utils.toFile` function will end up calling `fromYAML` instead of `toYAML` should it ever be used to parse a yaml file.

https://github.com/Praqma/helmsman/blob/f7d34b42fdc9d163d78cab780d02b504fb4908f2/utils.go#L134-L142

I couldn't find any calls to `toFile`, so this shouldn't impact any functionality at the time of creating this.

**Comment by luisdavim** [comment]
Well spotted @shaunmansell, I've opened a PR to address this.
