### ISSUE TITLE
Error: missing required TLS key file when creating tiller in namespace

### ISSUE THREAD

**Issue by regner** [Praqma/helmsman#139]
Here is the namespace part of my config:
```yaml
namespaces:
  kube-system:
    protected: false
    installTiller: true
    tillerServiceAccount: "tiller"
    caCert: "certs/ca.cert.pem"
    tillerCert: "certs/tiller.cert.pem"
    tillerKey: "certs/tiller.key.pem"
    clientCert: "certs/helm.cert.pem"
    clientKey: "certs/helm.key.pem"
  ingress:
    protected: false
  build:
    protected: false
  monitoring:
    protected: false
```

Here is the output of the apply:
```console
➜ helmsman -f helmsman.yaml --apply
 _          _
| |        | |
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | |
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v1.7.1
A Helm-Charts-as-Code tool.


2018/12/09 22:56:17 INFO: Parsed YAML [[ helmsman.yaml ]] successfully and found [ 7 ] apps.
2018/12/09 22:56:17 INFO: namespace validation -- Tiller is desired to be deployed with TLS in namespace [ kube-system ].
2018/12/09 22:56:17 INFO: namespace validation -- Tiller is NOT desired to be deployed in namespace [ ingress ].
2018/12/09 22:56:17 INFO: namespace validation -- Tiller is NOT desired to be deployed in namespace [ build ].
2018/12/09 22:56:17 INFO: namespace validation -- Tiller is NOT desired to be deployed in namespace [ monitoring ].
2018/12/09 22:56:19 WARN: I could not create namespace [ kube-system ]. It already exists. I am skipping this.
2018/12/09 22:56:20 WARN: I could not create namespace [ ingress ]. It already exists. I am skipping this.
2018/12/09 22:56:22 WARN: I could not create namespace [ build ]. It already exists. I am skipping this.
2018/12/09 22:56:24 WARN: I could not create namespace [ monitoring ]. It already exists. I am skipping this.
2018/12/09 22:56:24 INFO: deploying Tiller in namespace [ kube-system ].
2018/12/09 22:56:27 ERROR: while deploying Helm Tiller in namespace [kube-system]: Error: missing required TLS key file
```

My Helm version:
```console
➜ helm version
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Error: could not find tiller
```

I assume it isn't a path issue since if my path is wrong I get a different error:
```console
➜ helmsman -f helmsman.yaml --apply
 _          _
| |        | |
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | |
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v1.7.1
A Helm-Charts-as-Code tool.


2018/12/09 23:06:32 INFO: Parsed YAML [[ helmsman.yaml ]] successfully and found [ 7 ] apps.
2018/12/09 23:06:32 ERROR: namespaces validation failed  -- some certs/keys are not valid for Tiller TLS in namespace [ kube-system ].
```

Am I doing something wrong? I am confident in the certs as I tested creating a tiller install with the following command and it worked:
```console
➜ helm init \
--override 'spec.template.spec.containers[0].command'='{/tiller,--storage=secret}' \
--tiller-tls \
--tiller-tls-verify \
--tiller-tls-cert=tiller.cert.pem \
--tiller-tls-key=tiller.key.pem \
--tls-ca-cert=ca.cert.pem \
--service-account tiller
```

**Comment by regner** [comment]
With debug and verbose on I can see the actual helm init command being run:

```console
2018/12/09 23:56:56 VERBOSE: helm init --upgrade --service-account tiller --tiller-namespace kube-system --tiller-tls --tiller-tls-cert kube-system-tiller.cert --tiller-tls-key kube-system-tiller.key --tiller-tls-verify --tls-ca-cert kube-system-ca.cert
```

**Comment by regner** [comment]
I am NOT seeing this log line anywhere in the output: https://github.com/Praqma/helmsman/blob/abf0dc8cee5598adcf903445b0404039ec308520/utils.go#L251

Based on that it felt like the certs were not being copied to where helmsman wanted them to be. So I copied the required certs and named them what helmsman was expecting and it worked (well hit another problem, but thats a permissions problem so unrelated I believe).

Anyways, it appears the root of the issue is helmsman not copying the certs when they are local files.

**Comment by regner** [comment]
Thanks for being so quick to fix guys!

**Comment by arthurk** [comment]
Any chance to make a new release with this fix included? I want to try out helmsman but can't because of this bug

**Comment by sami-alajrami** [comment]
@arthurk This fix is now shipped in v1.7.2 :)

**Comment by cdbyrd** [comment]
@sami-alajrami I'm still seeing this problem in v1.7.4.  Is there something I'm missing?  The cert files are not getting copied.  I tried both relative and absolute file paths for the cert files.

```
$> helmsman -apply -f test-greenlight.yaml -verbose
 _          _
| |        | |
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | |
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v1.7.4
A Helm-Charts-as-Code tool.


2019/03/09 14:03:26 VERBOSE: kubectl client version: v1.13.3
2019/03/09 14:03:26 VERBOSE: Helm client version: v2.12.3+geecf22f
2019/03/09 14:03:26 INFO: Parsed YAML [[ test-greenlight.yaml ]] successfully and found [ 0 ] apps.
2019/03/09 14:03:26 INFO: namespace validation -- Tiller is desired to be DEPLOYED with TLS in namespace [ stage ].
...
2019/03/09 14:03:27 INFO: stage-tiller.cert will be used from local file system.
2019/03/09 14:03:27 INFO: stage-tiller.key will be used from local file system.
2019/03/09 14:03:27 INFO: stage-ca.cert will be used from local file system.
2019/03/09 14:03:27 INFO: stage-client.cert will be used from local file system.
2019/03/09 14:03:27 INFO: stage-client.key will be used from local file system.
2019/03/09 14:03:27 INFO: deploying Tiller in namespace [ stage ].
2019/03/09 14:03:27 VERBOSE: kubectl get serviceaccount stage-tiller-sa -n stage
2019/03/09 14:03:27 VERBOSE: helm init --upgrade --service-account stage-tiller-sa --tiller-namespace stage --tiller-tls --tiller-tls-cert stage-tiller.cert --tiller-tls-key stage-tiller.key --tiller-tls-verify --tls-ca-cert stage-ca.cert
2019/03/09 14:03:27 VERBOSE: helm list --tiller-namespace stage --tls --tls-ca-cert stage-ca.cert --tls-cert stage-client.cert --tls-key stage-client.key
2019/03/09 14:03:28 ERROR: while waiting for helm Tiller to be ready in namespace [ stage ] : Error: tls: first record does not look like a TLS handshake
```

**Comment by cdbyrd** [comment]
To clarify, the certs and keys are getting created in the working directory, but they do not seem to be referenced.  It seems like the copy happens after the search for the files, but it still fails if they are created before execution.  Here are the files in the working directory.

```
ls | grep stage
stage-ca.cert
stage-client.cert
stage-client.key
stage-tiller.cert
stage-tiller.key
```

**Comment by sami-alajrami** [comment]
@cdbyrd this looks like a problem with the certs you are using. Can you check if there is a problem with the certs you have. Try to manually use those certs with a helm command. If it does not work, then you have a problem with those certs.

As for the logs you shared, the files are actually copied into local directory and the helm command use them 
```
helm init --upgrade --service-account stage-tiller-sa --tiller-namespace stage --tiller-tls --tiller-tls-cert stage-tiller.cert --tiller-tls-key stage-tiller.key --tiller-tls-verify --tls-ca-cert stage-ca.cert

helm list --tiller-namespace stage --tls --tls-ca-cert stage-ca.cert --tls-cert stage-client.cert --tls-key stage-client.key
```
So everything looks fine from helmsman's point of view but it seems helm is having trouble talking to Tiller with those certs and logs this error `Error: tls: first record does not look like a TLS handshake`.

**Comment by cdbyrd** [comment]
The certs are good. I can stand up an instance of tiller with the same certs and connect.  However, using those certs in helmsman causes an error during provisioning of tiller.  The error states that it cannot find the cert files to create tiller.  It seems similar to the bug in this thread.  

--
Chris Byrd | 678.232.9875

**Comment by sami-alajrami** [comment]
@cdbyrd  can you share the logs with the error saying it can't find the certs so that we could check where/how it happens?
The logs you shared above give a different error that's coming from helm about TLS handshake.

**Comment by cdbyrd** [comment]
I think it may relate to a helm limitation when you are trying to upgrade the tiller instance and install certs after the initial helm init.  Looks like this is just a helm limitation at the moment.  If you want to use TLS you better do it at the start or there are some manual workarounds.

[Question: helm init --update tiller to enable TLS #4691](https://github.com/helm/helm/issues/4691)

**Comment by cdbyrd** [comment]
I can confirm the issue is related to the fact that the tiller deploy is not really declarative, it is more imperative.  Once tiller is installed, the DSF will not uninstall it (perform a helm reset).  The expectation is that if you changed the installTiller config from 'true' to 'false' that a `helm reset` would be performed.  This doesn't happen, therefore it impacts the following executions and can lead to varied results (breaking the idempotency of a declarative process.
