### ISSUE TITLE
Helmsman attempts to add repos that already exists

### ISSUE THREAD

**Issue by wilrnh** [Praqma/helmsman#143]
Running `helmsman --verbose` reveals that its attempting to run `helm repo add...` even if the repo defined in the DSF exists in `helm repo list`. This fails when `helm repo add` requires authentication, eg, `helm repo add ... --username.. --password`, so thats the bigger issue. However, changing this behavior to skip adding the repo if it exists seems like a reasonable fix.

**Comment by sami-alajrami** [comment]
I think we should support specifying these credentials to be passed from the DSF (through env vars for example) so that if you run Helmsman on a new env (where these repos don't exist), it will add them.

**Comment by sami-alajrami** [comment]
#214 will allow to set basic auth for repos that require it in the format
 `customeRepo = "https:user@pass:mycstuomrepo.org'` 

#201 allows to use preconfigured helm repos which are not configured by helmsman using the `preconfiguredHelmRepos` stanza. Example: 
```toml
preconfiguredHelmRepos = [ "myrepo1", "myrepo2" ]
```
