### ISSUE TITLE
Recreate Pods

### ISSUE THREAD

**Issue by ashleyjkell** [Praqma/helmsman#150]
In our current setup our docker images are tagged with the environment name they are deployed to. These don't change and when using Helm directly we pass "--recreate-pods" to ensure the pods have the latest version of the image. Unless I'm completely missing something there doesn't seem to be a flag to handle this in Helmsman apart from renaming the Chart every time. Could it be added?

**Comment by luisdavim** [comment]
Maybe we could add a `helmFlags` list to the DSF spec...

**Comment by luisdavim** [comment]
hi @ashleyjkell can you check if the solution provided in #161 solves your problem? I would appreciate it if you could test a build from by branch in your use case.
