### ISSUE TITLE
Support a tillerless setup

### ISSUE THREAD

**Issue by luisdavim** [Praqma/helmsman#151]
I think it would be cool to support the setup described here: https://rimusz.net/tillerless-helm/

**Comment by robbert229** [comment]
Hey, so perfect timing. I meant to open up an issue on supporting tillerless helm, but that didn't happen because you did it first. Collab?

**Comment by luisdavim** [comment]
Sure, I haven't started working on it, if you have, please goo ahead.

**Comment by tmc** [comment]
Any movement here?

**Comment by mkubaczyk** [comment]
Hi,
I've proposed #259 PR which is an answer for this (and expands the code from #152)
