### ISSUE TITLE
Helmsman only downloads certs with --apply

### ISSUE THREAD

**Issue by ironhalo** [Praqma/helmsman#169]
Helmsman only downloads helm certs when the `--apply` flag is called, this makes dry runs and plan without execution problematic when in a CI pipeline.

Would it be possible to both download the certs and clean them up when the execution finishes?

**Comment by sami-alajrami** [comment]
@ironhalo this happened in #101 (responding to #65) where I overlooked the `dry-run` operation. While `--dry-run` and `--apply` can't be run together. We can allow creating initializing helm when `--dry-run` is used.

**Comment by pwhitehead-cb** [comment]
thanks for the quick response!

**Comment by ironhalo** [comment]
thanks for the quick response!
