### ISSUE TITLE
Enable defining protected namespaces/applications

### ISSUE THREAD

**Issue by sami-alajrami** [Praqma/helmsman#17]
We need to enable users to define a set of namespaces/applications as desired to be `protected`to avoid messing up a production deployment. This can be added to the `desired state declarative file`

For that we need a definition of `protected`. I suggest the following:

1. Apps/Services (Helm releases) that are under protection CANNOT be deleted, upgraded or moved to other namespaces. 
2. Apps/Services CAN be moved into protection from a non-protected state. 
3. If a protected app/service need to be updated/changed or even deleted, this is possible .. but the protection has to be removed first (i.e. remove the namespace/app from the protected state).

The advantage of this feature is: if you are managing production and non-production apps/services in the same cluster (using different namespaces) from a single desired state file, then messing up a production system becomes harder as it requires two steps: **a) remove the protection b) do something crazy.** 

We can define protection at one of two levels:
1. At the namespace level: protection applies to any application in a protected namespace.
2. At the application level: each application definition can have a `protected` flag.

I am leaning towards the namespace level protection. It is a cleaner way as the protected namespaces will defined in their separate TOML table (section) in the `desired state file`. It also means making mistakes requires at least two edits in two different locations of the file which reduces the chances of accidental mistakes causing damage.

The protection feature will be optional. And we would still encourage users to maintain separate environments wherever possible and use different `desired state files` for different environments.

@meekrosoft @KamranAzeem  any thoughts on the protection definition and the approach to enforce it?

**Comment by meekrosoft** [comment]
This makes a lot of sense.  Is it possible to apply the protection on both namespaces and individual applications?

**Comment by sami-alajrami** [comment]
yes, it's possible. In that case, the namespace level protection would have higher precedence compared to the application level protection.
i.e. any application deployed  in a protected namespace is protected by default, otherwise, the application level protection flag would determine if an is protected or not.

**Comment by sami-alajrami** [comment]
This is now supported in v1.0.0.
