### ISSUE TITLE
helm-secrets look for wrong decrypt extension on chart upgrade

### ISSUE THREAD

**Issue by mam8270** [Praqma/helmsman#171]
On chart upgrade,  performs diff then upgrade. This code path appears to be erroneously appending secret suffix twice. This results in the file not opening. 

Command returned with exit code: . And error message: Error: open [file].secrets.yaml.dec.dec: no such file or directory

**Comment by sami-alajrami** [comment]
could you please share the snippet from your desired state file where you define the secret file(s) and the couple of logs before the error. Also, which helmsman version are you using?

**Comment by mam8270** [comment]
secretsFile Definition 

`[apps]
  [apps.contentstore]
    name = "contentstore-integ"
    valuesFiles = [
          "./common/qa_all.values.yaml",
          "./helm_vars/qa_all.values.yaml",
          "./common/integ.values.yaml",
          "./helm_vars/integ.values.yaml",
    ]
    secretsFiles = [
          "./common/qa_all.secrets.yaml",
          "./helm_vars/qa_all.secrets.yaml",
          #"./common/integ.secrets.yaml"
    ]`

helmsman version: v1.7.3-rc

**Comment by mam8270** [comment]
2019/01/16 20:23:06 VERBOSE: kubectl client version: v1.10.3
2019/01/16 20:23:06 VERBOSE: Helm client version: v2.11.0+g2e55dbe
2019/01/16 20:23:06 INFO: Parsed TOML [[ /helm/integ.toml ]] successfully and found [ 1 ] apps.
2019/01/16 20:23:06 INFO: Parsed TOML [[ /helm/qa_all.toml ]] successfully and found [ 1 ] apps.
2019/01/16 20:23:06 INFO: namespace validation -- Tiller is desired to be deployed WITHOUT TLS in namespace [ imaging ]. 
2019/01/16 20:23:06 INFO: namespace validation -- Tiller is NOT desired to be deployed in namespace [ kube-system ].
2019/01/16 20:23:06 VERBOSE: kubectl config use-context t17a
2019/01/16 20:23:06 INFO: deploying Tiller in namespace [ imaging ].
2019/01/16 20:23:06 VERBOSE: helm init --upgrade  --tiller-namespace imaging
2019/01/16 20:23:07 VERBOSE: helm list --tiller-namespace imaging
2019/01/16 20:23:07 VERBOSE: helm repo add imaging-helm-charts "s3://imaging-helm-charts/charts"
2019/01/16 20:23:08 VERBOSE: helm repo update 
2019/01/16 20:23:09 VERBOSE: helm inspect chart /helm/contentstore
2019/01/16 20:23:09 INFO: checking what I need to do for your charts ... 
2019/01/16 20:23:09 INFO: mapping the current helm state ...
2019/01/16 20:23:09 VERBOSE: helm list --all --max 0 --output json --tiller-namespace imaging
2019/01/16 20:23:10 VERBOSE: helm diff --suppress-secrets upgrade contentstore-integ /helm/contentstore -f /helm/common/qa_all.values.yaml -f /helm/helm_vars/qa_all.values.yaml -f /helm/common/integ.values.yaml -f /helm/helm_vars/integ.values.yaml -f /helm/common/qa_all.secrets.yaml.dec -f /helm/helm_vars/qa_all.secrets.yaml.dec --version "1.0.0"  --set imageTag="" --tiller-namespace imaging
imaging, spring-contentstore-integ, ConfigMap (v1) has changed:

2019/01/16 20:23:12 INFO: checking if any Helmsman managed releases are no longer tracked by your desired state ...
2019/01/16 20:23:12 VERBOSE: kubectl get configmap -n imaging -l MANAGED-BY=HELMSMAN
2019/01/16 20:23:13 INFO: no untracked releases found.
2019/01/16 20:23:13 INFO: sorting the commands in the plan based on priorities (order flags) ... 
----------------------
2019/01/16 20:23:13 INFO: Plan generated at: Wed Jan 16 2019 20:23:09
DECISION: release [ contentstore-integ ] is currently enabled and have some changed parameters. I will upgrade it! -- priority: 0
2019/01/16 20:23:13 INFO: sorting the commands in the plan based on priorities (order flags) ... 
2019/01/16 20:23:13 INFO: Executing the plan ... 
2019/01/16 20:23:13 VERBOSE: helm upgrade contentstore-integ /helm/contentstore --version "1.0.0" -f /helm/common/qa_all.values.yaml -f /helm/helm_vars/qa_all.values.yaml -f /helm/common/integ.values.yaml -f /helm/helm_vars/integ.values.yaml -f /helm/common/qa_all.secrets.yaml.dec.dec -f /helm/helm_vars/qa_all.secrets.yaml.dec.dec --force  --set imageTag="" --tiller-namespace imaging
2019/01/16 20:23:13 Command returned with exit code: . And error message: Error: open /helm/common/qa_all.secrets.yaml.dec.dec: no such file or directory

**Comment by mam8270** [comment]
initial diff succeeds using secretsFiles, but subsequent upgrade command fails (appears to be using duplicated file extension)

**Comment by sami-alajrami** [comment]
@mam8270 you are right. Can you please test #177. Thanks!
