### ISSUE TITLE
Feature request: secrets/values-files relative to the chart

### ISSUE THREAD

**Issue by erihanse** [Praqma/helmsman#172]
Currently the secrets and value files must reside relative to where the dsf file is. A chart may have other values files, e.g. values-prod, values-staging, values-test, etc. The way it is now, we need to fetch the chart manually before calling helmsman. I want the ability to be able to reference other values files within a chart, without having to pre-fetch the chart to the file system.

**Comment by sami-alajrami** [comment]
@erihanse I am not sure I understand your situation. Why do you need to fetch the chart files manually? and from where? Is it from another location in the same machine?

The reason why values/secret file paths need to be relative to the DSF is to allow users to run the helmsman CLI from any place and use the DSF file location (which you input in the CLI) the base for reaching secret/values files.

If you are fetching the files from the same machine, you just need to provide a relative path in your DSF  to those files instead of manually fetching them every time.  

If the location of the files keeps changing for some reason, you might want to have the different values files in a specific deployment directory and have a relative path to it.
Does that fix/answer your problem?

**Comment by erihanse** [comment]
Appreciate you getting back to me. I need to fetch the chart files manually, because we use values-files which are named different from the default `values.yaml`. 
Also, the values files reside not on the local filesystem, but in whatever chart repository we have released the charts to. 

```
our-nginx-chart/
├── Chart.yaml
├── environment
│   ├── prod
│   │   └── values.yaml
│   ├── systest
│   │   └── values.yaml
│   └── test
│       ├── secrets.yaml
│       └── values.yaml
├── README.md
└── templates
    ├── deployment.yaml
    ├── secret.yaml
    └── service.yaml
```
Imagine the example above. This is a chart that is released on whatever chart repository we use. We want to deploy this chart into a namespace, so we say in our dsf.yaml: 

```
apps:

  nginx-example:
    tillerNamespace: "namespace-test"
    chart: "chart-repository/nginx-example"
    version: "1.0.0"
    valuesFile: "our-nginx-chart/environment/test/values.yaml"
```

I'm not sure if it's a lot to ask for, but it would be nice if we didn't need to fetch this particular chart before we call helmsman.

**Comment by luisdavim** [comment]
I don't understand why making the paths relative to the chart instead of the DSF makes a difference. If they are on some other repo you still have to fetch them, if the problem is that you have to include the chart name in the path, you can use environment variables and set them in the same process that fetches the charts.

In my opinion, the values files are part of the state definition and they belong with the DSF. It's better to keep configuration logic separate from configuration data....

**Comment by erihanse** [comment]
I think what I really want is what they discuss here: https://github.com/helm/helm/issues/4275 and here: https://github.com/helm/helm/issues/2642. 

Ideally it should be supported by helm itself in the first place, but since it doesn't, it would be nice if helmsman let you fetch these things for you and clean up afterwards. We could have a field like: "remoteValuesFiles" and "remoteValuesFile", corresponding to what you do with values and secrets.

**Comment by luisdavim** [comment]
Oh, that's a completely different thing than what I understood what this was about. I'll take a better look once I'm on a computer. But as I've said. I really think that the values files are part of the desired state and should be together with the helmsman DSFs.

**Comment by erihanse** [comment]
Well. Helm is independent of helmsman. If we then switched from helmsman to something else (or just use helm) we would need to re-organise all values files accordingly. The values are specific to the charts where they are placed, and only makes sense in that context. 

It's just a bit of a hazzle that helm only supports the default filename when installing it (with the <remote>/<chartname> notation). If you want to use something else (e.g. values-systest.yaml) you need to fetch it first and untar it. What we like about helmsman is that you can specify a list of helm releases and their inputs (like values and secrets, namespace and so on). Sorry I didn't have time to make this shorter.

**Comment by luisdavim** [comment]
I understand that but I don't completely agree. I think that configuration data and configuration logic should be managed separately. Like for example in chef, you don't keep your data bags, roles and environment files together with your cookbooks. With helmsman or not I don't think that values files belong with the charts. But if you are using helmsman, both the values files and the helmsman DSFs are your desired state definition, your configuration data, so it makes sense to keep them together. How are helmsman files more or less coupled from the charts than the values files? With both you can keep a single file for each chart or one file for all charts or any combination in between...

**Comment by erihanse** [comment]
What you're saying makes sense. Thanks a lot for taking your time.

**Comment by musabmasood** [comment]
+1 we would like this too as we package multiple environment files directly inside the chart

**Comment by sami-alajrami** [comment]
@musabmasood as you can see in the comments above, it is better to keep the specific environment values files separate from the chart files. It is better to keep those environment files in a git repo where you can version control them and make use of a gitops approach to manage your deployments.

**Comment by musabmasood** [comment]
> @musabmasood as you can see in the comments above, it is better to keep the specific environment values files separate from the chart files. It is better to keep those environment files in a git repo where you can version control them and make use of a gitops approach to manage your deployments.

Our use case is an airgapped customer environment so we usually put a **images.yaml** file inside our chart's root. When we ship the images and chart to the environment, we untar the chart and install it with --values images.yaml. This file is same for all environments on customer's end, so we rather package it inside the chart than store it else where.

Would be great if --values could support files already inside the package (may be --values-local or something)

**Comment by luisdavim** [comment]
Is that supported by helm? How do you package the helmsman DSFs? Why not put them together in a DSF package? Anyway, it's hard to have support for both use cases, relative to DSF and relative to chart and I think the first one makes more sense for the reasons presented above. Have you tried using absolute paths? That should work, if it doesn't you can open a new issue for that.

**Comment by musabmasood** [comment]
> Is that supported by helm? How do you package the helmsman DSFs? Why not put them together in a DSF package? Anyway, it's hard to have support for both use cases, relative to DSF and relative to chart and I think the first one makes more sense for the reasons presented above. Have you tried using absolute paths? That should work, if it doesn't you can open a new issue for that.

we're not using helmsman at the moment.

**Comment by HamzaK8s** [comment]
@sami-alajrami I'm trying to implement the same approche I package my helm chart without values and I pushed it onto a nexus repository after that I create a repo git where I put the specific values.yaml and the requirement.yaml with chart name and repository URL's also I create a template directory where I put the common manifest
the command line  Helm dep update successfully got an update from the  chart repository but when I do 
```
helm install  git-chart/ -f values.yaml does not work 

```
why the helm install does not take in consideration the custom values.yaml 

Thanks

**Comment by luisdavim** [comment]
You're running helm directly not helmsman and the path to the values file must be absolute or relative to where you ran the command from.
