### ISSUE TITLE
Support cluster-admin tiller roles outside of kube-system

### ISSUE THREAD

**Issue by gregsidelinger** [Praqma/helmsman#180]
It would be nice if helmsman created tiller service accounts could be bound to cluster-admin when not in the kube-system namespace.  Having to create the namespace, service account and role binding before calling helmsman is kind of annoying.  The current behavior makes sense but I have use cases where I would rather not do a bunch of extra steps before calling helmsman.

**Comment by flyhard** [comment]
Seems like this is related to #125

**Comment by sami-alajrami** [comment]
this is shipped in v1.7.4
