### ISSUE TITLE
Helmsman said "release not installed" even if it is

### ISSUE THREAD

**Issue by KrustyHack** [Praqma/helmsman#192]
Ay,

Helmsman still want to install a release even if the release already exists and nothing changed in chart values (I've checked with `helm diff`).

Here the release `sqlproxy` was already installed with Helmsman 5min before and when replanning it says that it isn't installed.

Other apps work fine.

```yaml
  sqlproxy:
    namespace: "sqlproxy"
    enabled: true
    chart: "stable/gcloud-sqlproxy"
    version: "0.6.1"
    name: "sqlproxy"
    description: "SQLProxy"
    valuesFile: "sqlproxy.yaml"
    purge: false
    test: false
    protected: false
    wait: true
```

```
 _          _
| |        | |
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | |
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v1.7.3
A Helm-Charts-as-Code tool.


2019/02/12 10:27:46 INFO: Parsed YAML [[ plan.yaml ]] successfully and found [ 5 ] apps.
[...]
2019/02/12 10:27:46 INFO: namespace validation -- Tiller is NOT desired to be deployed in namespace [ sqlproxy ].
2019/02/12 10:27:49 INFO: GOOGLE_APPLICATION_CREDENTIALS is already set in the environment.
2019/02/12 10:28:04 INFO: checking what I need to do for your charts ...
2019/02/12 10:28:04 INFO: mapping the current helm state ...
2019/02/12 10:28:22 INFO: checking if any Helmsman managed releases are no longer tracked by your desired state ...
2019/02/12 10:28:22 INFO: no untracked releases found.
2019/02/12 10:28:22 INFO: sorting the commands in the plan based on priorities (order flags) ...
----------------------
2019/02/12 10:28:22 INFO: Plan generated at: Tue Feb 12 2019 09:28:04
[...]
DECISION: release [ sqlproxy ] is not installed. Will install it in namespace [[ sqlproxy ]] using Tiller in [ kube-system ] -- priority: 0
[...]
2019/02/12 10:28:22 INFO: completed successfully!
```

**Comment by KrustyHack** [comment]
Ay,

Nevermind, I'm stupid af.

For other with same problem : always `helmsman -f plan.yaml` before applying it... Or it isn't generated by Helsman.

Sorry for issue.

**Comment by KrustyHack** [comment]
/

**Comment by sami-alajrami** [comment]
no problem @KrustyHack .. can you run this command and see if `sqlproxy` is there in the output 
```
helm list --all --max 0 --output json --tiller-namespace kube-system  
```
also try this command and see if `sqlproxy` shows up (replace secrets with configmap if that's the storage backend you use):
```
kubectl get secrets -n kube-system -l MANAGED-BY=HELMSMAN
```

**Comment by KrustyHack** [comment]
Ay,

Thanks for the answer ! I will give a try asap as I migrated from Helmsman to Terraform.

**Comment by sami-alajrami** [comment]
thanks @KrustyHack .. since you moved to terraform, it is hard to tell if the second command would have returned no resources at the time when you faced the problem with helmsman.   

Generally speaking, when helmsman is making decisions, it looks for helm releases that are managed by itself (using the kubectl command above). If sql-proxy is deployed with helmsman, the helm release info will be labeled `MANAGED-BY=HELMSMAN`. Otherwise, if sql-proxy was installed in any other means, helmsman will not consider it when making decisions. 

If you use helmsman again and run into that problem, please run the kubectl command above and let us know  whether the helm release is correctly labeled or not.

**Comment by KrustyHack** [comment]
Ay,

Thanks for your answer.

The test I made with `sqlproxy-test` was totally independant from Terraform.
