### ISSUE TITLE
.kube/config.lock causes misleading error message

### ISSUE THREAD

**Issue by schollii** [Praqma/helmsman#197]
If there is a leftover ~/.kube/config.lock (by a process that used kubectl and crashed), then `helsmman --debug -f helmsman.yaml` gives this error: 
```
ERROR: failed to create context [ k8s-oliver2589.onsmartdev.media ] as you did not specify enough information in the Settings section of your desired state file.
```
Remove the lock file, and all works fine. Re-add the file (via say `touch ~/.kube/config.lock`) and the same error occurs. 

So the error message is very misleading and will cause (as it did in my case) to waste much time troubleshooting in places related to settings, ie completely unrelated to the lock. Luckily as part of troubleshooting I eventually had to use kops, and kops failed with a very clear error "open /home/tooluser/.kube/config.lock: file exists".

**Comment by sami-alajrami** [comment]
@schollii how do you define the context in your DSF and which helmsman version are you using?
The error message above is only supposed to happen when you want the context to be created and you didn't provide one of the following in the settings section in the DSF: `username`, `password`, `clusterUri`

**Comment by sami-alajrami** [comment]
on another note, if you are using multiple kubeconfig files, you may specify which kubeconfig to use with `--kubeconfig <path to your kubeconfig>` .. alternatively, you can use your current defined context by not specify `kubeContext` in your DSF and helmsman would respect the current context. See PR #159  for details on this.

If helmsman does not see a current context or the context you point to is not visible as a result of the lock file, helmsman will attempt to create a context and then will say it is missing credentials etc to create the context. 

I will make the error message more clear about what's exactly missing.
