### ISSUE TITLE
question/feature: Templating configmap in value.yml 

### ISSUE THREAD

**Issue by MichalPloski** [Praqma/helmsman#199]
Hi everyone,
We plan to migrate from plain helm to helmsman - mostly because in our production workflow we rely heavily on ordering. 
For non production workflow we are looking for a option to template our configmap in vaules.yml file with a variables provided by previous CI steps ( namespace name, database url i.e) Is it possible to achieve this? 
In documentation we can see option to template values.yaml with environment variables but it looks like we could use only simple, not nested structure.
Example:

``` apps]
  [apps.noname-app]
    namespace = "staging"
    enabled = true
    chart = "chartmuseum/noname-app"
    version = "0.1.0"
    name = "noname-app"
    valuesFiles = [
      "values/noname-app/defaults.yaml"] 

  [apps.noname-app.set]
   APP_URL="https://nonameapp-${NAMESPACE}.${DOMAIN}"   
   BOOKKEEPER_URL="https://xxxr-${NAMESPACE}.${DOMAIN}"
   HOST="nonameapp-${NAMESPACE}.${DOMAIN}"
```
defaults.yaml:

```
configmap:
 APP_URL="https:/nonameapp-NAMESPACE.DOMAIN"
 BOOKKEEPER_URL="https://xxxr-NAMESPACE.DOMAIN"
 HOST="nonameapp-NAMESPACE.DOMAIN"
```

I tried to modify variables in config_map by using set directive in helmsman config, but i don't see option to provide nested variables. NAMESPACE  and DOMAIN is accessible to helmsman via environment variable ( using env file)

So, how can we template values using nested variables? Is there any plans to add this feature?

**Comment by sami-alajrami** [comment]
Hi @MichalPloski your [apps.noname-app.set] looks fine. Helmsman should interpolate all your environment variables (if they exist). This is done using go's ExpandEnv() 
```
ExpandEnv replaces ${var} or $var in the string according to the values of the current environment variables. References to undefined variables are replaced by the empty string.
```

You can verify what's being passed to your helm chart from helmsman by running: 
```
helm get noname-app | grep -i APP_URL
```

On a side note, you have to make sure you are referring to the right variables in your `set` stanza. For example, if the value file for your chart has APP_URL under SERVER , then your set should look like:

```
[apps.noname-app.set]
   "SERVER.APP_URL"="https://nonameapp-${NAMESPACE}.${DOMAIN}"
```

**Comment by MichalPloski** [comment]
Hi @sami-alajrami Thank you for your support. Adding prefix to variable as mentioned by you in last part of a comment solved my problem

**Comment by sami-alajrami** [comment]
you are welcome :)
