### ISSUE TITLE
 helmsman should show diff when upgrading a chart

### ISSUE THREAD

**Issue by rellu** [Praqma/helmsman#200]
When you upgrade a chart to newer version and use `-show-diff` option plan will only tell you that chart will be upgraded. I believe it should also show the diff of what it will actually change like it shows if I only change some value.

It's also not uncommon for us that we change some value and upgrade a chart in the same PR. In some scenarios it's even needed e.g. if a change in chart requires a change in values. 

Is there some reason why the diff is not shown when upgrading? I am also happy if there's some new option like `-show-diff-on-upgrades` to allow this.

If I manually run `helm diff upgrade -f myvalues.yaml mychart myrepo/mychart --version=<up-by-one>` I can see the diff just fine.

**Comment by sami-alajrami** [comment]
Hi @rellu `--show-diff` should print the diff result in the logs. This works both while doing plan or apply.
`helmsman --show-diff -f example.yaml `
I have just tried this with helmsman v1.7.4

The reason why it's not shown by default is that it might log some sensitive info and it can clutter the logs when there are many apps being upgraded.

**Comment by InfinityGone** [comment]
@sami-alajrami, I'm seeing the same behavior. The key is when you update a chart version, say from 2.0.0 to 2.0.1, `--show-diff` doesn't show anything. `helm diff` does. I see the same behavior on v1.7.4 and v1.8.1.

I can likely put together a small demo if it would be helpful. Let me know.

**Comment by gordonbondon** [comment]
Looks like this was fixed here https://github.com/Praqma/helmsman/pull/221

**Comment by sami-alajrami** [comment]
closing this since it is fixed.
