### ISSUE TITLE
Feature Deploying apps in parallel

### ISSUE THREAD

**Issue by MichalPloski** [Praqma/helmsman#202]
As far as I understand if we have a bunch of apps in toml file we are able to manipulate order of deployment and all  of releases will be run sequentially which for some cases is a big waste ( most of our apps are separated from each other and can be deployed in pararell). Maybe we could provide behaviour that setting same priority for multiple apps leads to pararell deployment of those apps.

**Comment by skeenan947** [comment]
why was this closed?  It's a very valid feature request, unless I'm missing something and it's already supported.

**Comment by MarcinGinszt** [comment]
Where it is already supported? Documentation is silent about it

**Comment by MarcinGinszt** [comment]
Oh, I've got it.  `wait` parameter must be set to `false`, as in default
