### ISSUE TITLE
Make settings optional

### ISSUE THREAD

**Issue by erihanse** [Praqma/helmsman#203]
I'm trying to let helmsman determine the kube context from current-context. I cannot run this without atleast one setting specified in the dsf. This works to me:
```
settings:
  password: "asdf"
```
while this doesn't work:
```
settings:
 # password: "asdf"
```

**Comment by erihanse** [comment]
Error message:
`ERROR: settings validation failed -- no settings table provided in state file.`

**Comment by sami-alajrami** [comment]
shipped in v1.8.0
