### ISSUE TITLE
AWS IAM machine credentials are not used

### ISSUE THREAD

**Issue by ironhalo** [Praqma/helmsman#207]
I'm running helmsman in CD as a container on an ec2 instance while storing helm TLS certs in S3.  Helmsman requires the AWS credentials to be exposed as environmental variables and does not seem to respect the credentials presented by the IAM role attached to the instance.  My workaround have been to extract the credentials from the metadata endpoint, is it possible to use the already available credentials natively?

**Comment by ironhalo** [comment]
Looks like the source of the error is from this function?

https://github.com/Praqma/helmsman/blob/master/aws/aws.go#L38

**Comment by sami-alajrami** [comment]
should be fixed in v1.8.1 @ironhalo please reopen if the issue persists.
