### ISSUE TITLE
Helmsman should show version when using -no-banner parameter

### ISSUE THREAD

**Issue by nvtkaszpir** [Praqma/helmsman#209]
Use case:
As an end user I'd like to be able quickly get helmsman version without any complex output parsing.

Example command
```bash
helmsman -v -no-banner
```
Expected output:

```bash
helmsman -v -no-banner
helmsman_version: v1.7.4
```

Actual output
```bash
helmsman -v -no-banner
2019/03/06 09:35:12 INFO: No desired state files provided.
```

As you can see the helmsman version is in banner.

current output without `-no-banner`
```bash
helmsman -v
 _          _ 
| |        | | 
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \ 
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | | 
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v1.7.4
A Helm-Charts-as-Code tool.


2019/03/06 09:32:09 INFO: No desired state files provided.
```
This means that we need to parse ASCII art to extract helmsman version.

**Comment by kpucynski** [comment]
`2019/03/06 09:32:09 INFO: No desired state files provided.`
Why it is expecting state file when it is explicitly asked for version?
