### ISSUE TITLE
Tiller deployment should be declarative like applications

### ISSUE THREAD

**Issue by cdbyrd** [Praqma/helmsman#216]
Tiller is deployed via configuration in the DSF.  The tiller deployment should follow the same declarative model used by applications.  
- If the "installTiller" property is set to true, and tiller is not installed, tiller should be installed with the defined configuration using the `helm init` command.  
- If the "installTiller" property is set to false, and tiller is installed, tiller should be uninstalled with using the `helm reset` command.
- If neither of those are true, then nothing needs to change.  

The current behavior is that tiller will be installed, if not available in a namespace and requested for the namespace.  However, tiller will not be uninstalled if configuration is changed to not install tiller in the namespace.

Tiller does not respond well to configuration changes, at least tiller 2.x.  Therefore, the best bet is to allow a reset of tiller, and then a re-install with the desired parameters.  Currently, that is not possible through helmsman.  Reference the comments in #139 for an example of this behavior.

**Comment by bigbellyburger** [comment]
If this happens there needs to be another way to get helmsman to ignore the `kube-system` namespace. I'm currently doing this by setting `installTiller: false` for `kube-system`, which makes it ignore anything deployed to that namespace.

My use-case is that I have several helmsman instances connecting to the same kubernetes cluster, and each should only manage a subset of the namespaces.
