### ISSUE TITLE
Better support for multiple helsman instances managing the same cluster

### ISSUE THREAD

**Issue by bigbellyburger** [Praqma/helmsman#217]
Currently multiple helmsman instances, each with their own desired state files, can be used with the same cluster, give that they all disable the `kube-system` namespace by setting `installTiller: false`.

This feels a bit fragile, and if for some reason two helmsman instances would use the same namespace things wouldn't go as expected.

It would be nice if it was possible to tell helmsman what its instance name is, which is then used for the value of the `MANAGED-BY` label.

**Comment by sami-alajrami** [comment]
thanks @bigbellyburger .. you are right and we plan to fix this in the near future.
This was discussed in #173  .. So I would close this issue in favour of the older one.
