### ISSUE TITLE
Pass Helm values file to docker container

### ISSUE THREAD

**Issue by RickS-C137** [Praqma/helmsman#225]
Hello guys,

I just discovered Helmsman and it sounds pretty interresting, but I have to admit that the docs have room for improvement. So there's a question I have but I can't find anything about it. So when using the Docker container in a CI pipeline, you pass the DSF to it. But what is with the Helm values files you specify in the DSF? How are they passed/copied into the docker container and which path do I need to set for them in the DSF?

**Comment by sami-alajrami** [comment]
hi @RickS-C137 .. we would love to have PRs improving/complementing the existing docs ..
for your question, you can start your CI job by cloning your git repo inside the container and that should ideally include your DSF as well as any other values files. 
Some CI providers have a special command you add in your CI config file and it clones the repo for you automatically. E.g., CircleCI for has the built-in step [checkout](https://circleci.com/docs/2.0/configuration-reference/#checkout) other providers probably have similar steps. Alternatively, you can simply run a `git clone` command. The docker images contain git.

Alternatively, you could mount your files with a volume to the docker container, but I prefer the previous way.
Hope this helps!

**Comment by RickS-C137** [comment]
Hi @sami-alajrami , atm I'm working on another thing, but will come back to this in the next weeks. This sound definitely helpful. So thank you very much! We're using Atlassian Bamboo. When I got it running I can document the steps to get it running here, if you like.

**Comment by sami-alajrami** [comment]
Sure, that would be great!
