### ISSUE TITLE
Feature: Deploy only specific namespace.app

### ISSUE THREAD

**Issue by fmotrifork** [Praqma/helmsman#230]
I would love to be able to set a target (or a list of targets) for the `helmsman -apply` so i can iterate faster.
This will allow us to 

- Only check the state in the cluster for the specified app for faster state check
- Be multiple people working on different apps in the same shared helmsman repo

**Comment by mkubaczyk** [comment]
Hi @fmotrifork, I've just proposed a new PR #237 that would introduce such feature. :-)

**Comment by mkubaczyk** [comment]
Since #237 was merged recently, will you @sami-alajrami be preparing a new release containing that soon? I can't wait to get my hands on a release with this feature. :-)

**Comment by sami-alajrami** [comment]
this is shipped in v1.9.0 :)
