### ISSUE TITLE
Is it possible to disable the initial search?

### ISSUE THREAD

**Issue by sharkymcdongles** [Praqma/helmsman#244]
That step takes like 30 minutes for our deployment. All of our version tags are put into our deployment file via pipelines, so the search step is very very pointless for us. Is there some way to bypass it with a flag or something? I couldn't find anything in the documentation.

If not are there plans to add it?

Basically 30 min for the search step then 5 min for the update meant it takes 35 min to update when it could just take 5.

**Comment by sharkymcdongles** [comment]
Other option would be to have it search for multiple things at once instead of going slowly line by line.

**Comment by krogon** [comment]
Does `--target` flag helps you?
https://github.com/Praqma/helmsman/blob/master/docs/how_to/misc/limit-deployment-to-specific-apps.md#limit-execution-to-explicitly-defined-apps

**Comment by sharkymcdongles** [comment]
@krogon Not really because we run it from a pipeline and have like 90 microservices deploying with it. Target would only work if we only wanted to run it against single services. We want to be able to update all faster.

**Comment by sami-alajrami** [comment]
@sharkymcdongles by search, are you referring to the validation if charts exist? If so, you could use `--skip-validation` to skip those checks.

**Comment by sharkymcdongles** [comment]
Yes the initial chart search. If the chart isn't there I don't care if it
fails then. The search adds so much time for no reason from my perspective.

**Comment by sharkymcdongles** [comment]
Any update on this? I could submit a pull request, but if there is disagreement over this topic it won't get merged and will be useless work on my end. Could add a new flag like --skip-initial-search or something along those lines.

**Comment by sami-alajrami** [comment]
@sharkymcdongles didn't `--skip-validation` solve the issue for you?

**Comment by sharkymcdongles** [comment]
@sami-alajrami sorry for the way way way way too late reply. I just tested with --skip-validation on 3.4.4, and it still does the initial search. From debug log:

```
 2020-06-23 09:07:14 DEBUG: helm show chart x/x --version 0.1.1
 2020-06-23 09:07:15 DEBUG: helm search repo chart x/x --version 0.1.1-o json
 2020-06-23 09:07:15 DEBUG: helm show chart chart x/x --version 0.1.1
 2020-06-23 09:07:17 DEBUG: helm search repo chart x/x --version 0.1.1 -o json
```

Command used:

`helmsman --debug --ns-override $NAMESPACE --skip-validation --no-ns -p 3 -f dsf.yaml --apply --keep-untracked-releases --migrate-context default`
