### ISSUE TITLE
Feature Request: Support custom stable URLs

### ISSUE THREAD

**Issue by ironhalo** [Praqma/helmsman#245]
By default Helm is initialized with https://kubernetes-charts.storage.googleapis.com as the default stable URL.  Please add support for initializing helm with a custom stable URL.

`helm init --stable-repo-url ...`

**Comment by sami-alajrami** [comment]
@ironhalo you can already override the default with your own by defining it in the helm repos stanza:

```yaml
helmRepos:
  stable: "https://your-custom-stable"
```

**Comment by ironhalo** [comment]
Thanks for the reply and sorry for the slow response.  I was able to test this today without success

My redacted DSF
```
helmRepos:
  stable: "https://[proxy]/artifactory/googleapis-remote/kubernetes-charts"
```

This is the output from my CI pipeline (gitlab) where I'm unable to reach googleapis.com.
```
2019/07/24 23:30:11 VERBOSE: helm init --force-upgrade --service-account tiller-mosaic --tiller-namespace mosaic --tiller-tls --tiller-tls-cert mosaic-tiller.cert --tiller-tls-key mosaic-tiller.key --tiller-tls-verify --tls-ca-cert mosaic-ca.cert --override 'spec.template.spec.containers[0].command'='{/tiller,--storage=secret}'
2019/07/24 23:30:11 ERROR: while deploying Helm Tiller in namespace [mosaic]: Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: read tcp 172.17.0.3:37078->172.217.10.112:443: read: connection reset by peer
```

I'm able to successfully run things locally since I'm not behind the same firewall.

**Comment by sami-alajrami** [comment]
thanks @ironhalo for clarifying this. It did not work because helmsman initializes helm before adding the repos (including overriding stable) .. I have changed the order in PR #271 .. you can test this with this image `praqma/helmsman:pr-271`
