### ISSUE TITLE
error converting YAML to JSON

### ISSUE THREAD

**Issue by messiahUA** [Praqma/helmsman#246]
I've been successfully using helmsman v1.8.1, but after upgrade to 1.9.0 it stops working because of:

> Command returned with exit code: . And error message: Error: failed to parse helmsman-temp-files/prometheus.yaml: error converting YAML to JSON: yaml: line 1297: mapping values are not allowed in this context
> Error: plugin "diff" exited with error

prometheus has a lot of different values starting with $ and now they all get substituted thus breaking yaml

https://github.com/Praqma/helmsman/pull/240

**Comment by eperdeme** [comment]
The quick fix is to use the escape method in Helmsman which would be $$ looking at the original MR - https://github.com/Praqma/helmsman/pull/122.

**Comment by sami-alajrami** [comment]
@messiahUA as @eperdeme said, you can escape those values with `$$`
we could add a flag to disable substitution in values files

**Comment by messiahUA** [comment]
ok, thanks

**Comment by sami-alajrami** [comment]
a new flag `--no-env-subst` is now available after merging #249
