### ISSUE TITLE
Helmsman is removing untracked releases even with -target flag

### ISSUE THREAD

**Issue by mkubaczyk** [Praqma/helmsman#254]
Even though -target flag is set to chart X, helmsman removes untracked Y release.
I would suppose targeting would scope it to specific chart only no matter what step of helmsman invoking it is.

And since I'm aware of -keep-untracked-releases flag, I still think this should not be required when target is set, because setting proper scope should have a precedence over such flag.

**Comment by gdubicki** [comment]
I think this is a dangerous bug and should be resolved quickly. +1 to PR.
