### ISSUE TITLE
encrypted secrets files not being decrypted by helmsman even if secrets plugin present

### ISSUE THREAD

**Issue by schollii** [Praqma/helmsman#256]
helmsman version: 1.6.3

We have found that our helmsman setup does not decrypt secrets files before using them. Here is our folder containing files: 

    helmsman.dsf
    values.yaml
    secrets.sops.yaml

and the helmsman.dsf has this: 

    valuesFiles: 
    - values.yaml
    secretsFiles: 
    - secrets.sops.yaml

and we have the helm secrets plugin installed AND if I run "helm secrets install -f values.yaml -f secrets.sops.yaml" everything works. But if we run helmsman in that folder it catches only the values.yaml not the secrets.sops.yaml. 

The helmsman docs suggest that having the secrets plugin is sufficient, but perhaps there is another setting to change, in the DSF or some config file? 

The [code here](https://github.com/Praqma/helmsman/blame/dad6d649c54bf7393b88c1f0a785483e7f652516/decision_maker.go#L351) suggests it should work in latest but I think that fix might have been added in 1.7, crap, might need to upgrade...

**Comment by schollii** [comment]
I'm trying 1.9.1 and getting this: 

```
shell$ helmsman --apply --keep-untracked-releases -f helmsman.yaml
 _          _ 
| |        | | 
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \ 
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | | 
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v1.9.1
A Helm-Charts-as-Code tool.


2019/06/03 16:24:16 INFO: substituting env variables in values and secrets files ...
2019/06/03 16:24:16 INFO: Parsed YAML [[ helmsman.yaml ]] successfully and found [ 23 ] apps.
2019/06/03 16:24:16 INFO: namespace validation -- Tiller is NOT desired to be deployed in namespace [ environment-testing ].
2019/06/03 16:24:17 WARN: I could not create namespace [ environment-testing ]. It already exists. I am skipping this.
2019/06/03 16:24:17 INFO: deploying Tiller in namespace [ kube-system ].
2019/06/03 16:25:15 INFO: checking what I need to do for your charts ... 
2019/06/03 16:25:15 INFO: mapping the current helm state ...
2019/06/03 16:25:40 Command returned with exit code: . And error message: Error: forwarding ports: error upgrading connection: error sending request: Post https://OUR_K8S_CLUSTER/api/v1/namespaces/kube-system/pods/tiller-deploy-5f5b8d99f4-dtlnm/portforward: dial tcp: lookup OUR_K8S_CLUSTER on 192.168.7.1:53: read udp 172.17.0.2:33077->192.168.7.1:53: i/o timeout
```
Any idea what's going on? There was no port forwarding attempt in 1.6.3 that I'm aware of. The 192.168.7.1 is my work LAN gateway address.

**Comment by schollii** [comment]
I was able to upgrade helmsman to 1.7.4. The 1.9.1 will have to be re-visited once we have time to figure out the above error about port forwarding.

**Comment by chrisduong** [comment]
I have no issue with v1.12.0
