### ISSUE TITLE
Option to output rendered helm .yaml files to other pipe

### ISSUE THREAD

**Issue by nvtkaszpir** [Praqma/helmsman#261]
Feature request:
Right now helmsman shows diff or rendered templates from hel in output if requested, but the problem is that everything is sent to stdout.

Would be nice to have rendered helm output to another pipe or file, which later on can be for example passed to other tools for additional inspection before pushing it to kubernetes.

**Comment by galindro** [comment]
An option could be used to it. Maybe `--raw`
