### ISSUE TITLE
Problems with helmFlags in v1.10.0

### ISSUE THREAD

**Issue by lachlancooper** [Praqma/helmsman#264]
As of v1.10.0 user-supplied `helmFlags` are no longer passed to `installRelease()`, `upgradeRelease()`, or `reInstallRelease()`. This comes from changes in #259, perhaps as a result of adapting an older PR.

Additionally, #252 effectively added a number of extra flags including `--timeout` to `helm diff upgrade`. This is not supported by helm-diff and results in the following error if `timeout` is set in the DSF:
```
Command returned with exit code: . And error message: Error: unknown flag: --timeout
```

Since very few flags are common to all helm commands, I would suggest we need to split these into separate arrays (`helmFlags` and `helmDiffFlags`, for example).

**Comment by mkubaczyk** [comment]
Hi,

I've caught same thing trying out 1.10.0 during envs deployment. I'll be trying to fix it and come with PR for this.

**Comment by mkubaczyk** [comment]
#265
