### ISSUE TITLE
Helm v3

### ISSUE THREAD

**Issue by luisdavim** [Praqma/helmsman#274]
Has anyone tested Helm v3? What kind of changes would be needed in Helmsman to support it?

**Comment by sami-alajrami** [comment]
I haven't tried it yet .. but from the description of the changes (and from the top of my head):
- the part of Helmsman dealing with Tiller will no longer be needed. 
- Helm 3 will allow releases of the same chart to use the same name in different namespaces which might require some code change in how Helmsman makes decisions.
- There might be some changes to how repositories are used.
- Additionally, helm helpers functions would need to be adapted to any changes in Helm 3 client.

**Comment by mkubaczyk** [comment]
Hi,

first of all, do we want to extend current code to optionally support v3 or to introduce a breaking change and drive the helm 3 specific version of helmsman?

**Comment by sami-alajrami** [comment]
I think the support for v3 will be a breaking change and thus shouldn't be limited by trying keep backward compatibility in Helmsman. We should aim for a new version targeting helm v3 IMHO.

**Comment by mkubaczyk** [comment]
+1
this would be a great opportunity to clean up the code significantly. Should be start a separate branch for this?

**Comment by sami-alajrami** [comment]
@mkubaczyk yes

**Comment by mkubaczyk** [comment]
FYI, in my spare time I'm working on it here https://github.com/mkubaczyk/helmsman/tree/helm-v3

**Comment by anandp-ib** [comment]
hi

**Comment by mkubaczyk** [comment]
It's been humongous work so far, but we're close to the end I'd say.
Tiller-related parts were removed, logging has been reconfigured to follow some standard, changed lots of messages and aligned the logic of helmsman to helm 3 (since some things have changed).
Tests were also updated.
I've been testing it with rc1 of helm 3. Seems to work for both helm-secrets and hiera-eyaml secrets.
At this point I'd like you guys @luisdavim @sami-alajrami to dive into my branch maybe and verify the changes and discuss everything that is causing some questions to arise. 

And maybe we can follow the same gitflow Helm has chosen, that is they created branch to continue v2 support and master has started to be v3?

**Comment by mkubaczyk** [comment]
Since v3 was just released https://helm.sh/blog/helm-3-released/ let’s focus on releasing at least beta helmsman 3 to support it. My PR still waits for some reviews :-)

**Comment by luisdavim** [comment]
Thanks for working on this. I'm currently travelling so it might take me a while to get to review the changes.

**Comment by paksu** [comment]
Any progress on this? Would be awesome to try it out!

**Comment by iamaverrick** [comment]
Any progress on this? currently waiting for helmsman support of helm 3 thanks

**Comment by sami-alajrami** [comment]
@paksu @iamaverrick helmsman 3.0.0-beta1 was releases a few days ago.

**Comment by luisdavim** [comment]
Is there anything missing before we move out of beta a do an official v3 release? Any known issues?

**Comment by sami-alajrami** [comment]
No issues on my end. I haven't tested the latest beta but if no issues are reported by users in the next week or so, we can cut the official release.
It would be great to have all the breaking changes released with the v3.0.0 , so if we still need to do any improvements which might introduce breaking changes, it should happen before v3.0.0 GA release.

**Comment by luisdavim** [comment]
Yes, that makes sense. One thing that I've noticed is that in v3 the flags for expanding variables in the DSF and values files have been reversed, I think we should change their names to reflect this change, flags with no in their names indicate their control something that is on by default.

**Comment by sami-alajrami** [comment]
Makes sense. Let's change their names and review all the available flags!
