### ISSUE TITLE
Helmsman diff incorrectly parses `$` variables from ConfigMap

### ISSUE THREAD

**Issue by sc250024** [Praqma/helmsman#276]
**UPDATE**: Tested on latest version `v1.11.0`, same result.

* **I'm submitting a ...**
  - [X] bug report
  - [X] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

I'm not sure if this is a feature, or a bug, but it's related to the `--show-diff` flag.

* **What is the current behavior?**

Helmsman incorrectly (I think?) tries to interpolate a multi-line `ConfigMap` from NGINX (or anything else really) that has variables starting with `$` as BASH variables.

For example, I have an NGINX configuration; here's a snippet:

```yaml
nginx:
  conf: |-
    ## server configuration
    server {
      listen {{ .Values.nginx.internalPortHttp }};
      location / {
        return 301 https://$host$request_uri;
      }
    }
    server {
      listen {{ .Values.nginx.internalPortHttps }} ssl http2;

      if ($http_x_forwarded_proto = '') {
        set $http_x_forwarded_proto  $scheme;
      }
```

When running the command:

```shell
$ helmsman \
--dry-run \
--show-diff \
--suppress-diff-secrets \
--target myapp \
-f mycluster.yaml
```

I get the following diff output from the snippet above:

```diff
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: myapp
    labels:
      app: myapp
      chart: myapp-1.0.0
      heritage: Tiller
      release: myapp
  data:
    myapp.conf: |-
      ## server configuration
      server {
        listen 80;
        location / {
-         return 301 https://$host$request_uri;
+         return 301 https://;
        }
      }
      server {
        listen 443 ssl http2;
-       if ($http_x_forwarded_proto = '') {
-         set $http_x_forwarded_proto  $scheme;
+       if ( = '') {
+         set   ;
        }
```

I know it's parsing variables in my BASH shell because when I do this:

```shell
$ export host='this'
$ export request_uri='-shouldnt-happen'
$ export http_x_forwarded_proto='or-should-it?'
```

And re-run the command again, I get the following:

```diff
      server {
        listen 80;
        location / {
-         return 301 https://$host$request_uri;
+         return 301 https://this-shouldnt-happen;
        }
      }
      server {
        listen 443 ssl http2;
-       if ($http_x_forwarded_proto = '') {
-         set $http_x_forwarded_proto  $scheme;
+       if (or-should-it? = '') {
+         set or-should-it?  ;
        }
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Anything with a `ConfigMap` that has variables in it starting with `$` should reproduce the results.

* **What is the expected behavior?**

Anything in a multi-line `ConfigMap` entry should be processed literally, unless via Mustache brackets `{{ }}` from the Helm chart itself.

* **What is the motivation / use case for changing the behavior?**

I'm scared Helmsman will break deploys if it's not fixed 😅

* **Please tell us about your environment:**
  
Helmsman version: **Helmsman version: v1.11.0**
Helm version: 

```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
```

**Comment by AmirAliSobhGol** [comment]
This problem only occurs within values files.
i have the same issue with prometheus rules that i define in values.yaml.

**Comment by sami-alajrami** [comment]
Hi @sc250024 & @AmirAliSobhGol yes, by default Helmsman tries to substitute any string starting with $ from environment variables .. to avoid this, there are two options:
1) if you don't wish to substitute environment variables anywhere, you can use the `--no-env-subst` flag to turn off environment substitution globally.
2) If you would like to use some environment variables but also want to keep some strings with `$` as they are, you can let helmsman escape the `$` by adding another `$` in front. E.g. `$$http_x_forwarded_proto`. 
Hope this helps?

**Comment by sc250024** [comment]
@sami-alajrami Ah yes, that should do the trick.
