### ISSUE TITLE
Unclear errorr on wrong path in repository

### ISSUE THREAD

**Issue by MarcinGinszt** [Praqma/helmsman#278]
If Helmsman tries to install a Chart, that has a wrong path in the index.yaml, it spits out following error:

`Command returned with exit code: . And error message: Error: open /root/.helm/cache/archive: is a directory
Error: plugin "diff" exited with error`

which is pretty confusing

**Comment by sami-alajrami** [comment]
@MarcinGinszt this error comes from the helm diff plugin .. if you run helmsman with the `--verbose` you will get the actual helm command causing this error and that might give an idea about the underlying cause.
