### ISSUE TITLE
Ability to disable env substitution only in value files

### ISSUE THREAD

**Issue by medzin** [Praqma/helmsman#280]
Env variable substitution in desired state files is a very useful feature and I use it for dynamically generated test environments, but now when the substitution has been extended to the values files it causes problems with accidental value substitution (e.g. a lot of randomly generated passwords and command definitions contain `$` sign). I would be cool to disable substitution in value files so the state file could remain dynamic and values files static.

I can prepare PR if this functionality is acceptable.

**Comment by eperdeme** [comment]
Would this be an optional flag to disable substitution in values files? We make heavy use of the values files to inject variables in to our helm charts.

**Comment by medzin** [comment]
To be backwards compatible this flag should be optional and by default set to false.
