### ISSUE TITLE
Add support for totango/helm-ssm

### ISSUE THREAD

**Issue by sethatron** [Praqma/helmsman#292]
This Helm plugin allows SSM Parameters in S3 to be defined as expression in Helm that evaluate to the value of the SSM Parameter, like:

` htpasswd: "{{ssm /mgmt/docker-registry/htpasswd us-east-1}}"`

I'm not sure which aspect of Helm vs. Helmsman is preventing these plugins from being read in, but when I view the output of the Chart, the "{{ssm ...}}" value is returned instead of the parameter.

Would this be a trivial feature to support? It would greatly improve the flexibility of Helmsan if plugins could be used

**Comment by emilhdiaz** [comment]
@sethatron I have a WIP PR (https://github.com/Praqma/helmsman/pull/295) open for adding SSM Param support directly to Helmsman, would that still meet the requirement here?

**Comment by sethatron** [comment]
Yes, your PR will also extend environment variable support which is currently unsupported in totango/helm-ssm. I can close this request if that PR will be merged soon.

**Comment by sami-alajrami** [comment]
this was shipped in v1.13.0. 
I will go ahead and close this issue.
