### ISSUE TITLE
Issue overriding default helm repos

### ISSUE THREAD

**Issue by TechDawg270** [Praqma/helmsman#294]
I edited my desired state specification to include the following:

```
helmRepos:
  stable: "https://artifactory-internal/artifactory/googleapis-remote/kubernetes-charts"
```
Which resulted in an unexpected failure due to a default also needing to be specified for "incubator". Without setting a value for "incubator" it defaults to a URI not accessible due to the company firewall. In order to use our internal artifactory as a proxy I ended up with the following desired state specification

```
helmRepos:
  stable: "https://artifactory-internal/artifactory/googleapis-remote/kubernetes-charts"
  incubator: "https://artifactory-internal/artifactory/googleapis-remote/kubernetes-charts"
```

Is that the intended behavior? In my opinion only a "stable" repo should be required and "incubator" optional. If this is the intended behavior a note to detail that [here in the docs](https://github.com/Praqma/helmsman/blob/master/docs/desired_state_specification.md#helm-repos) would be useful for clarity

**Comment by luisdavim** [comment]
@TechDawg270 does #304 solve your problem?

**Comment by TechDawg270** [comment]
That fix should suffice. I would say this can be closed as a result of that work
