### ISSUE TITLE
Helmsman runs `helm diff` with even with `-show-diff` off

### ISSUE THREAD

**Issue by sc250024** [Praqma/helmsman#296]
Greetings,

I'm running Helmsman in a CI/CD pipeline using two stages: **validate** and **apply**. In the **validate** stage, I run the following command against my cluster:

```shell
$ helmsman \
  --dry-run \
  --force-upgrades \
  --kubeconfig ${KUBECONFIG} \
  --no-env-subst \
  --show-diff \
  --suppress-diff-secrets \
  --verbose \
  -f my-cluster.yaml
```

This results in a full validation, and a full diff of the changes that I want to see for verification. Next, in my **apply** stage, I run the following command:

```shell
$ helmsman \
  --apply \
  --force-upgrades \
  --no-env-subst \
  --suppress-diff-secrets \
  --verbose \
  -f my-cluster.yaml
```

Which is fine, but strangely, `helmsman` goes through the complete `helm diff` workflow once again, which can be _quite_ slow.

1. How do I get `helmsman` to NOT show the diff for my apply stage?
2. In general, which set of flags result in `helmsman` simply applying the changes as quickly as possible for the **apply** stage? 

Thank you!

**Comment by luisdavim** [comment]
The `--show-diff` flag is not for enabling the diff plugin it's just to display it's output. I think that what you want is na new feature flag to disable the diff plugin.

**Comment by mmccord-mdbuyline** [comment]
If I do a dry-run I'm getting the diff regardless of whether `-show-diff` is present or not. Additionally, when I do a dry-run, secrets are displaying regardless of whether `-suppress-diff-secrets` is on or off.

**Comment by mehyedes** [comment]
I am using this command
```
helmsman -dry-run -p 4 -f apps.toml
```
I can see all the supplied values, even if they are secrets. Tried the `-suppress-diff-secrets` flag but it seems that it's not available anymore in the latest version.
Any other way to disable `-show-diff` ?
