### ISSUE TITLE
recreate-pods returning Invalid

### ISSUE THREAD

**Issue by sethatron** [Praqma/helmsman#299]
I'm using:

`...

    set:
      clusterAgent.enabled: true
      datadog.apiKeyExistingSecret: datadog-monitoring-api-key
      image.tag: latest-jmx
    helmFlags: [
      "--recreate-pods",
    ]
...
`

And it is returning: `Command returned with exit code: . And error message: Error: unknown flag: --recreate-pods`

Version: 1.11.0

**Comment by nvanheuverzwijn** [comment]
I would recommend you to not rely on --recreate-pods but on a hash value in your annotations of your deployment based on some configuration files or on a generated datetime in your labels.

See this : https://github.com/helm/helm/issues/5218

Also, the problem may be that the --recreate-pods is only available in the upgrade command of helm and not the install. Not sure how helmsman handle this.
