### ISSUE TITLE
Docker build is failing

### ISSUE THREAD

**Issue by luisdavim** [Praqma/helmsman#312]
The docker build is failing with:
```
./plan.go:31:11: undefined: aurora.GrayFg
```

**Comment by luisdavim** [comment]
@mkubaczyk Any ideas? I can build it on my laptop but the build fails in docker.

**Comment by mkubaczyk** [comment]
I know what's wrong, I'm preparing PR

**Comment by luisdavim** [comment]
Ok, cool. But it's strange because it builds just fine outside of Docker.

**Comment by mkubaczyk** [comment]
It's just a matter of how we pull dependencies

**Comment by luisdavim** [comment]
Looks like that didn't work....

**Comment by luisdavim** [comment]
oh, wait. it did. but I was expecting to see a new latest build on dockerhub. do you know how that works?

**Comment by mkubaczyk** [comment]
unfortunately I'm not aware of the dockerhub build's configuration, which would be helpful here :-)
