### ISSUE TITLE
Passing list to helm --set

### ISSUE THREAD

**Issue by estei** [Praqma/helmsman#319]
I might be using a feature in an unintended way, but here goes.

I am currently trying to pass a dynamically generated list of ip addresses to a helm chart in a setup.toml file. 
This is [valid helm syntax](https://github.com/helm/helm/blob/7cbed3f77bd771dfb46c63733c497e8c05225422/docs/using_helm.md#the-format-and-limitations-of---set) with `{item1, item2}` as the value

Example of the config (IP addresses will later be converted to environment vars, but for now hard coded)
```
[apps.monitoring]
    enabled = true
    namespace = "monitoring"
    name = "monitoring"
    chart = "stable/prometheus-operator"
    valuesFile = "monitoring-values.yaml"
    version = "6.21.0"
    test = false
    tillerNamespace = "helm"
    [apps.monitoring.set]
      "kubeEtcd.endpoints" = "{192.168.50.101}"
      "kubeScheduler.endpoints" = "{192.168.50.101}"
      "kubeProxy.endpoints" = "{192.168.50.101, 192.168.50.102}"
      "kubeControllerManager.endpoints" = "{192.168.50.101}"
```

It works perfectly as long as there is only one item in the lists, but as soon as there are more items I get errors because the comma in the passed in value is escaped with a `\`
I think the problem is on the below line where a string replace of commas is done on the value.
https://github.com/Praqma/helmsman/blob/916e438e11defc399b0f5724860e6c33aff7bbec/decision_maker.go#L411

The error I get from the kubernetes API when helmsman tries to create the endpoint from the above example

```
Command returned with exit code: . And error message: Error: failed to create resource: Endpoints "monitoring-prometheus-oper-kube-proxy" is invalid: [subsets[0].addresses[0].ip: Invalid value: "192.168.50.101, 192.168.50.102": must be a valid IP address, (e.g. 10.9.8.7), subsets[0].addresses[0].ip: Invalid value: "192.168.50.101, 192.168.50.102": must be a valid IP address]
```

The command it runs when setting verbose output:
Notice the extra `\`before the comma in `--set kubeProxy.endpoints="{192.168.50.101\, 192.168.50.102}" `
```
VERBOSE: helm upgrade monitoring stable/prometheus-operator -f .helmsman-tmp/tmp938094804/monitoring-values.yaml --version "6.21.0" --force  --set kubeControllerManager.endpoints="{192.168.50.101}" --set kubeEtcd.endpoints="{192.168.50.101}" --set kubeScheduler.endpoints="{192.168.50.101}" --set kubeProxy.endpoints="{192.168.50.101\, 192.168.50.102}" --tiller-namespace helm
```

**Comment by luisdavim** [comment]
Hi, try using `setString` instead of `set`.

**Comment by eperdeme** [comment]
Hello @estei , 

Did you ever get this to work ? Seems to do the same under setstring.

**Comment by eperdeme** [comment]
I can't actually find anyway to do what I want;

So result in the Helm chart yaml needs to be similar to the below, but it changes per environment we work in.
```
webproxies:
    - 192.168.1.1/32
    - 192.168.1.2/32
    - 192.168.1.3/32
```

I can't find anyway to pass in variable based lists to Helm via helmsman either via set/setstring or valuesfile.

**Comment by estei** [comment]
Sadly no 😟
I ended up generating a second values file, from our inventory, with the lists. This file I then reference together with the original values file in the setup.toml file. The valuesFiles property will merge the values files.

**Comment by eperdeme** [comment]
Ah, fair enough.
I worked around it by editing the upstream chart and doing;
```
webproxies: 
  - ${webproxy_a}
  - ${webproxy_b}
  - ${webproxy_c}
```

Then setting in envs;
```
webproxy_a=100.1.209.2/32
webproxy_b=100.1.210.3/32
webproxy_c=100.1.212.4/32
```
Hacky, but I can get on with my day.

**Comment by estei** [comment]
Getting on with our day and solving the problem at hand will always trump the perfect solution. 

Yours is a good solution when the number of web proxies doesn’t change or the chart supports empty values.

**Comment by walidkhlg** [comment]
Any update on this ? still facing this issue on **v3.16.
In my case the list is fetched from an external source, even though the elements do not change frequently, it would be nice to be able to pass it with an environment variable without having to do like this:
```
    set: # https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
      controller.service.type: LoadBalancer
      # -- Restrict access For LoadBalancer service. Defaults to 0.0.0.0/0.
      #controller.service.loadBalancerSourceRanges: "{$SOURCE_RANGE_LIST}"
      controller.service.loadBalancerSourceRanges[0]: xxxxxx
      controller.service.loadBalancerSourceRanges[1]: yyyyyy
      controller.service.loadBalancerSourceRanges[2]: zzzzzz
      ...
```
