### ISSUE TITLE
use `--output json` when possible

### ISSUE THREAD

**Issue by luisdavim** [Praqma/helmsman#327]
The new version of helm added the `--output json` option to most commands. We should take advantage of that since it's much cleaner and robust to parse json than parsing tabular outputs.
https://helm.sh/blog/2019-10-22-helm-2150-released/

**Comment by mkubaczyk** [comment]
We're using it everywhere we could find a place for that to replace uglier tabular outputs parsing. Do you think current state on v3 is enough to consider this done?

**Comment by luisdavim** [comment]
Yes, I would say so. Thanks.
