### ISSUE TITLE
Helmsman evaluating $

### ISSUE THREAD

**Issue by ivelichkovich** [Praqma/helmsman#330]
I have a values file with $ in it. When I deploy with regular helm it works fine, when I deploy with helmsman anything with a $ is missing. Here are examples from the configmap that is deployed.

helmsman
replacement: /api/v1/nodes//proxy/metrics
...
replacement: ':'
...
      - alert: NodeDiskPressure
        annotations:
          description: Node `{{ .node }}` showing Disk Pressure
          summary: Node showing DiskPressure
        expr: kube_node_status_condition {condition="DiskPressure", status="true"} ==
          1
        for: 3m
        labels:
          severity: critical

vs helm
replacement: /api/v1/nodes/${1}/proxy/metrics
...
replacement: $1:$2
...
      - alert: NodeDiskPressure
        annotations:
          description: Node `{{ $labels.node }}` showing Disk Pressure
          summary: Node showing DiskPressure
        expr: kube_node_status_condition {condition="DiskPressure", status="true"} ==
          1
        for: 3m
        labels:
          severity: critical

Also helmsman fails on yaml to json mapping on some regex fields where helm doesn't and they needed to be quoted to even pass through i.e. 
regex: ([^:]+)(?::\d+)?;(\d+) 
works in helm but not helmsman

**Comment by eperdeme** [comment]
Unsure on the yaml->json element, but the $'s character is used for variable substitution.
 
https://github.com/Praqma/helmsman/blob/master/docs/desired_state_specification.md

You can use environment variables in the desired state files. The environment variable name should start with "$", or encapsulated in "${", "}". "$" characters can be escaped like "$$".

Starting from v1.9.0, you can also use environment variables in your helm values/secrets files.

**Comment by ivelichkovich** [comment]
Ahh yeah, thank you, just realized that was the issue and recently upgraded past 1.9 to get that feature and then forgot about it... thanks again
