### ISSUE TITLE
`brew install helmsman` installs helm 3 as dependency

### ISSUE THREAD

**Issue by brorbw** [Praqma/helmsman#331]
The title says it all

**Comment by anthony-coder** [comment]
Currently ran into this error. Burned some cycles figuring this one out

**Comment by chenrui333** [comment]
I will fix this.

**Comment by chenrui333** [comment]
@brorbw @anthony-coder I have just merged a fix, can you give a try? Thanks!!

**Comment by sami-alajrami** [comment]
@chenrui333 is it also fixed for helmsman v3.0.0 to use helm v3?

**Comment by chenrui333** [comment]
@sami-alajrami I used helmv2 for the formula. I think per helmsman upgrade, we can bump the dependency to helmv3.

What is the upgrade path for helmsman users?

**Comment by chenrui333** [comment]
Filed a PR for v3.0.0 GA, https://github.com/Homebrew/homebrew-core/pull/48672

**Comment by chenrui333** [comment]
@sami-alajrami I have updated the formula to v3.0.0 GA, can you take a look at the above PR. I will probably get it merged soonish.

**Comment by sami-alajrami** [comment]
Closing as I believe this is now resolved.
