### ISSUE TITLE
Does helmsman support creating secrets via env vars?

### ISSUE THREAD

**Issue by marcelloromani** [Praqma/helmsman#335]
i read in #54 "Currently, helmsman supports passing secrets via environment variables."

What does that mean? I haven't found an example in the documentation.
Maybe I missed something obvious?

The functionality I'm thinking about is creating a secret in a specific namespace taking e.g. username and password values from respecitve environment variables.

Happy to contribute a doc PR if needed.

**Comment by orefalo** [comment]
Same question here, I am puzzled around helmsman support around secrets

**Comment by luisdavim** [comment]
No, Helmsman will not generate k8s secrets for you, what that means is that you can use env variables in the DSF instead of having them in plain text.

**Comment by orefalo** [comment]
Sorry guy, I am a beginner.

Simple question, how would you translate the bellow?

```
kubectl --namespace openfaas --from-literal=basic-auth-user=admin \
    --from-literal=basic-auth-password=admin \
    create secret generic basic-auth
```

**Comment by luisdavim** [comment]
That command is not used in Helmsman afaik.
I think that would create a secret that would look something like this:
```
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: openfaas
data:
  basic-auth-user: YWRtaW4K
  basic-auth-password: YWRtaW4K
```

but for this type of questions you're better off asking them in the Kubernetes Slack https://kubernetes.slack.com/archives/C09NXKJKA

**Comment by marcelloromani** [comment]
@luisdavim thans for the reply, but what is DSF in "what that means is that you can use env variables in the DSF instead of having them in plain text" ?

**Comment by luisdavim** [comment]
You should read the docs. DSF stands for desired state file.

**Comment by marcelloromani** [comment]
Thanks
