### ISSUE TITLE
helmsman 3.0.0-beta1 not able to find helm charts without v1 release

### ISSUE THREAD

**Issue by mayppong** [Praqma/helmsman#348]
I recently migrated charts over to helm 3, and now I'm trying out helmsman 3.0.0-beta1. When I try to run `helmsman -f helmsman.yaml` however, I get this message.
```
2019-12-23 19:00:27 CRITICAL: Error from server (NotFound): secrets "sh.helm.release.v1.fluentd.v1" not found
```

It seems like helmsman couldn't detect that I already have newer revisions of helm chart installed, and that the revision v1 of the chart has been deleted from the historical record keeping.
```
sh.helm.release.v1.fluentd.v18                             helm.sh/release.v1                    1      4d18h
sh.helm.release.v1.fluentd.v19                             helm.sh/release.v1                    1      4d18h
sh.helm.release.v1.fluentd.v20                             helm.sh/release.v1                    1      4d18h
sh.helm.release.v1.fluentd.v21                             helm.sh/release.v1                    1      4d18h
sh.helm.release.v1.fluentd.v22                             helm.sh/release.v1                    1      4d18h
sh.helm.release.v1.fluentd.v23                             helm.sh/release.v1                    1      4d18h
sh.helm.release.v1.fluentd.v24                             helm.sh/release.v1                    1      4d18h
sh.helm.release.v1.fluentd.v25                             helm.sh/release.v1                    1      4d18h
sh.helm.release.v1.fluentd.v26                             helm.sh/release.v1                    1      4d18h
sh.helm.release.v1.fluentd.v27                             helm.sh/release.v1                    1      4d18h
```

**Comment by luisdavim** [comment]
have you converted your releases from `ConfigMaps` to `Secrets`?

**Comment by sami-alajrami** [comment]
this caused by this line https://github.com/Praqma/helmsman/blob/9ce249b97c6a3a4fd53058b6b1b78ac72da94cee/internal/app/kube_helpers.go#L329

I wasn't aware that v1 could disappear from history  .. we may need to use the latest revision in the line above instead of hardcoded v1.

**Comment by mayppong** [comment]
I did not see any of the releases in ConfigMaps, I think the helm migration plugin did that job for me already.

Thank you both of you for the prompt response, and taking time out of the holiday season to fix this for me :)
