### ISSUE TITLE
support a bit better variable munging

### ISSUE THREAD

**Issue by tibers** [Praqma/helmsman#35]
My golang isn't good enough to pull this off but I see that [variable substitution is limited to the names of variables but no string interpolation](https://github.com/Praqma/helmsman/blob/dec253e7268fa76406763bddd8d60ec9f9b431d8/state.go#L158-L166).

This means that a desirable behavior like `appName = "MySimpleApp.$fqdn"` can't happen, even though it seems like a natural pattern since `appName = "$HOSTNAME"` can because the code finds the leading `$` and looks up the environment variable.

I'd like to propose the normal pattern of `STRING-$VARIABLENAME-STRING` where the code would understand that any patterns of letters after a `$` is a variable name.

**Comment by nicolaiskogheim** [comment]
To remove the requirement to not have alphanums after a variable name in shell scripting (sh, bash, etc.), an alternate syntax is used: `${HOSTNAME}`, which means you could have `STRING${VARIABLENAME}STRING` if you so desire. Might be worth considering to allow the option of curly braces, or even just straight out require those braces.

**Comment by tibers** [comment]
I think the project is dead. We moved onto helmfile: https://github.com/roboll/helmfile

**Comment by nicolaiskogheim** [comment]
Thanks for the heads-up and for the alternative!

**Comment by sami-alajrami** [comment]
@tibers @nicolaiskogheim apologies for the late response as I was away from this for awhile .. and thanks for this fix :)
