### ISSUE TITLE
Dockerhub builds are failing 

### ISSUE THREAD

**Issue by luisdavim** [Praqma/helmsman#352]
I don't know if it's just for the beta tags but the dockerhub builds have been failing on recent pushes to master.

**Comment by sami-alajrami** [comment]
this has been caused by changing the path of the Dockerfile in recent changes. I have updated the dockerhub autobuild config with the right path and now the build works. This didn't auto-build the tags , so if there is any tag missing, I can build and push them manually.  Just let me know.

**Comment by luisdavim** [comment]
this seems to be fixed now, thanks.
