### ISSUE TITLE
should we disable adding stable/incubator helm repos by default?

### ISSUE THREAD

**Issue by sami-alajrami** [Praqma/helmsman#359]
Helm 3 [no longer sets repos by default](https://helm.sh/docs/topics/v2_v3_migration/#overview-of-helm-3-changes):

```
local or stable repositories are not set-up by default
```
Helmsman v3.0.0-betaX still adds those repos by default and we have  a flag to disable that behaviour. Should we reverse this (not add repos by default and provide a flag to add them) to be aligned with the helm 3 behaviour? Or the current behaviour is good enough? 

Any thoughts @luisdavim @mkubaczyk

**Comment by eperdeme** [comment]
My thoughts is we should not add any repos by default and not have the feature flag. Instead maybe put in the example helmsman file adding the stable/incubator repos.

**Comment by mkubaczyk** [comment]
Let’s do what @eperdeme says. No flag at all, no default repos added, let’s make it explicitly required in order to add any repo. :-)

**Comment by luisdavim** [comment]
I agree with @mkubaczyk and @eperdeme
