### ISSUE TITLE
Modify or skip helm init

### ISSUE THREAD

**Issue by PascalGomolka** [Praqma/helmsman#366]
Hi,

we are using Kubernetes v1.16 and helm in version 1.12.0.

For my understanding the api support changed in this kubernetes version:
apiVersion: extensions/v1beta1 is not supported anymore.

Now if I try to deploy an update of my code with the follwing helm command I get the following issue:

helmsman --verbose -f $MIP_FILE --skip-validation --ns-override $NAMESPACE --apply

2020/01/03 11:42:25 VERBOSE: kubectl client version: v1.16.1
2020/01/03 11:42:25 VERBOSE: Helm client version: v2.12.21+g7d2b0c7
2020/01/03 11:42:25 INFO: substituting env variables in values and secrets files ...
2020/01/03 11:42:25 INFO: Parsed YAML [[ file.yaml ]] successfully and found [ xxx ] apps.
2020/01/03 11:42:25 INFO: desired state validation is skipped.
2020/01/03 11:42:25 VERBOSE: kubectl config use-context my-context
2020/01/03 11:42:25 VERBOSE: helm init --client-only 
2020/01/03 11:42:39 VERBOSE: helm repo add  stable "https://kubernetes-charts.storage.googleapis.com"
2020/01/03 11:42:41 VERBOSE: helm repo update 
2020/01/03 11:42:52 VERBOSE: kubectl create namespace my-namesapce
2020/01/03 11:42:52 WARN: I could not create namespace [ my-namespace ]. It already exists. I am skipping this.
2020/01/03 11:42:52 INFO: overriding apps namespaces with [ mip-qc ] ...
2020/01/03 11:42:52 INFO: overriding namespace for app:  my-service
....
2020/01/03 11:42:52 INFO: deploying Tiller in namespace [ my-namespace ].
2020/01/03 11:42:52 VERBOSE: kubectl get serviceaccount tiller -n my-namespace
2020/01/03 11:42:52 VERBOSE: helm init --force-upgrade --service-account tiller --tiller-namespace my-namespace --override 'spec.template.spec.containers[0].command'='{/tiller,--storage=secret}'
2020/01/03 11:42:53 [1;31mERROR: while deploying Helm Tiller in namespace [my-namespace]: Error: error installing: the server could not find the requested resource

Is there a way to disable the **helm init --force-upgrade --service-account tiller --tiller-namespace my-namespace --override 'spec.template.spec.containers[0].command'='{/tiller,--storage=secret}'** step or modify this one with a piped sed command at the end?

Thanks a lot

**Comment by luisdavim** [comment]
Hi, if `helm init` is trying to create a new deployment using `apiVersion: extensions/v1beta1` this means that the version of `helm` that you are using is too old for the cluster that you're trying to use it with if tiller is already deployed using `apiVersion: extensions/v1beta1` and `helm init` is trying to update it to use `apps/v1`.
I think this is more of helm issue than a helmsman issue.

**Comment by PascalGomolka** [comment]
Yep. you are right. thx for support

**Comment by luisdavim** [comment]
Oh, I forgot to mention, you can disable the tiller installation **or** use the tillerless mode, check the docs on the v1.x branch https://github.com/Praqma/helmsman/blob/1.x/docs/desired_state_specification.md
