### ISSUE TITLE
Helmsman is trying to read secrets from all namespaces

### ISSUE THREAD

**Issue by epierotto** [Praqma/helmsman#368]
helmsman version: v3.0.0-beta6
helm version: v3.0.0

I have only one namespace defined in my DSF file but Helmsman is trying to get all the secrets across all namespaces, which is failing since that I'm restricting the access of the service account.

I think that Helmsman should limit the search to resources within the namespaces defined in the DSF file.

```bash
295 2020-01-03 17:01:04 INFO: Preparing plan...
296 2020-01-03 17:01:04 INFO: Acquiring current Helm state from cluster...
297 2020-01-03 17:01:04 DEBUG: helm list --all --max 0 --output json --all-namespaces
298 2020-01-03 17:01:05 INFO: Checking if any Helmsman managed releases are no longer tracked by your desired state ...
299 2020-01-03 17:01:05 DEBUG: kubectl get secret --all-namespaces -l MANAGED-BY=HELMSMAN -o custom-columns=NAME:.metadata.name,NS:.metadata.namespace,CTX:.metadata.labels.HELMSMAN_CONTEXT --no-headers
300 2020-01-03 17:01:05 CRITICAL: Error from server (Forbidden): secrets is forbidden: User "system:serviceaccount:kube-system:pipeline" cannot list resource "secrets" in API group "" at the cluster scope
```

**Comment by luisdavim** [comment]
I'll open a PR to fix this.

**Comment by epierotto** [comment]
I see that now the `kubectl get secret` is limited to the namespaces from the DSF file.
There is still and issue with this command:
```
helm list --all --max 0 --output json --all-namespaces
```
https://github.com/Praqma/helmsman/blob/master/internal/app/helm_release.go#L26

In Helm 3 the output of that command returns an empty list if the user does not have enough permissions, also it returns a 0 exit code.

```
helm list --all --max 0 --output json --all-namespaces
[]

echo $?
0
```
