### ISSUE TITLE
helmsman 3.0.0-beta4 `--help` text contains misprints

### ISSUE THREAD

**Issue by mayppong** [Praqma/helmsman#370]
```
  -no-env-values-subst
        turn off environment substitution in values files only. (default true). (default true)
```
and 
```
  -suppress-diff-secrets
        don't show secrets in helm diff output. (default true). (default true)
```
probably didn't need to print `default true` twice.

**Comment by sami-alajrami** [comment]
thanks for reporting @mayppong .. this is already fixed in v3.0.0-beta6 when these flags got deprecated. Instead of `--no-env-values-subst`, there is now the flag `--subst-env-values` which enables substitution of env vars in values files. That is switched off by default.
