### ISSUE TITLE
[feature request] Support for HashiCorp Vault Secrets

### ISSUE THREAD

**Issue by Xtigyro** [Praqma/helmsman#374]
Hey Team,

Are there any plans for including basic support for HashiCorp Vault secrets?

**Comment by sami-alajrami** [comment]
yes, that was planned at some point after v3.0.0 GA release. However, there is still no timeline for it.

**Comment by Xtigyro** [comment]
Very nice! Thank you!

That might be useful as a start (found it yesterday by chance): https://github.com/roboll/helmfile/pull/906

**Comment by Xtigyro** [comment]
Hey @sami-alajrami - are there any updates about this feature req.?

**Comment by sami-alajrami** [comment]
@Xtigyro unfortunately, I didn't have a chance to work on it. Would you be able to start a PR for this?

**Comment by orefalo** [comment]
If I may... isn't the feature indirectly implemented via hiera-eyaml ?

The page https://github.com/voxpupuli/hiera-eyaml. talks about plugins.. and especially, the vault plugin : https://github.com/crayfishx/hiera-eyaml-vault
