### ISSUE TITLE
Helmsman apply issue (release web-crm failed: timed out waiting for the condition)

### ISSUE THREAD

**Issue by gdajuk** [Praqma/helmsman#390]
Hi guys,

I’ve my helmsman deployment set, which works properly for more than 10 kubernetes microservices. Now, I add additional microservice, and it's installing properly, but my CircleCi deployment finished like that:

1. First run (when No helm package is installed/build):
	`Command returned with exit code: 1. And error message: Error: release www-crm failed: timed out waiting for the condition` 
2. Second run (helm package is in FAILED state):
	`Command returned with exit code: 1. And error message: Error: UPGRADE FAILED: "www-crm" has no deployed releases`

The core run command looks like that: 
`helmsman -apply -keep-untracked-releases -show-diff -debug -f helmsman/15-front.yaml`

Few facts:

- The depoyment runs via CircleCi pipeline,
- Helm repos are set in GCP Storage
- All other apps works properly.
- Yaml file for this app is set exactly the same as for other apps.
- I am able to install this app manually via helm install, but the deployment failing during the helmsman step
- After failed deployment commands:

> root@f10d7f08babd:/project# helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "myorg" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
root@f10d7f08babd:/project# 
root@f10d7f08babd:/project# 
root@f10d7f08babd:/project# helm search www-crm
NAME           	CHART VERSION	APP VERSION	DESCRIPTION                      
myorg/www-crm	0.1.2        	1.0        	A Helm chart for FrontEnd service
root@f10d7f08babd:/project# 
root@f10d7f08babd:/project# 
root@f10d7f08babd:/project# helm ls www-crm
NAME                 	REVISION	UPDATED                 	STATUS  	CHART               	APP VERSION	NAMESPACE
www-crm              	1       	Tue Jan 21 11:24:22 2020	FAILED  	www-crm-0.1.1       	1.0        	dev02    
www-crm-nginx-ingress	1       	Fri Jan 17 14:51:04 2020	DEPLOYED	nginx-ingress-1.29.2	0.27.0     	dev02
root@f10d7f08babd:/project# 
root@f10d7f08babd:/project# 
root@f10d7f08babd:/project# gsutil ls gs://myorg/ |grep www-crm
gs://myorg/www-crm-0.1.0.tgz
gs://myorg/www-crm-0.1.1.tgz
root@f10d7f08babd:/project# 

During the investigation stage, I found the version difference using helm search and helm ls... Now wondering, why `helm search www-crm` shows version 0.1.2 (which is not deployed), and do not exist on my Storage Bucket? Also why it doesn't show other versions?

The interesting thing.. is that service itself is deployed properly, the only issue is that helmsman deployment finishing with this error, and helm package is in `FAILED` state.

**Comment by luisdavim** [comment]
HI, `failed: timed out waiting for the condition` seems like an error coming from helm, does your chart use any pre or post install hooks? from what you're getting, it sounds like you have a post install hook. You can try increasing the helm timeout property in the helmsman file to allow the post install hook to finish or check if any of the hooks are failing.

**Comment by gdajuk** [comment]
No, I don't think there are any pre/post install hooks. Chart is very simple, what I did:
1. helm create mychart
2. Adjust values.yaml 
    - image +tag (from which component package should be build)
    - fullnameoverride
    - ingress (k8s annotations + hosts + tls setup
3. deploy via helmsman using core command which I paste above.

The 15-front.yaml file looks like that:

> metadata:
  org: "mydomain"
  maintainer: "myself"
  description: "some desc"

> settings:
  kubeContext: "gke_my_context.."
  serviceAccount: "tiller"

> helmRepos:
  stable: "https://kubernetes-charts.storage.googleapis.com"
  incubator: "http://storage.googleapis.com/kubernetes-charts-incubator"
  myrepo: "gs://myrepo"

> namespaces:
  kube-system:
    protected: false
    installTiller: true
    tillerServiceAccount: "tiller"
  test01:
    protected: false
    installTiller: false

> apps:
  www-crm:
    name: "www-crm"
    description: "FrontEnd chart"
    namespace: "test01"
    enabled: true
    chart: "myrepo/www-crm"
    version: "0.1.23"
    valuesFile: ""
    purge: false
    test: false
    priority: -10
    wait: true
    timeout: 600
    set:
      image.tag: "0.0.30"

**Comment by luisdavim** [comment]
If it doesn't have any hooks that could be taking some extra time to finish the only other reason I can think of is a slow helm repo or docker reg. Have you tried setting the timeout to something longer than the default?

**Comment by gdajuk** [comment]
As you see above, timeout for this app was set to 10minutes, and it's even too much, as its a simple static front-end service.. Other java micro-services installed using same helmsman script and configuration are deployed in the same way in 1/2minutes... Any other clue, how can I get more debugging options?

**Comment by luisdavim** [comment]
Do you have the same issue if you try to deploy the chart with helm directly?

**Comment by gdajuk** [comment]
No, whenever I run `helm install --name mydeploy --namespace myNS chart/` chart is installed properly in valid version (0.1.1). Whenever I do that with helmsman, it failed with ingress, and when I run `helm repo search` I still get this weird old version 0.1.2 ...

**Comment by luisdavim** [comment]
In the sample you posted above, you are requesting `version: "0.1.23"`....
Also, can you try the latest version of Helmsman?

**Comment by gdajuk** [comment]
Just fix that.. There was a typo - version was 0.1.1.

Honestly, today I build another charts in version 0.1.3 and set it in helmsman template. The situation is exactly the same, even the version are the same now.. 

Very strange thing, when installing it manually from downloaded charts with `helm install` it works, whenever I run `helmsman -apply ...` with enabled ingress service it fails.

I am using version 1.10.0, should I go with latest 3.0? Not sure if its compatible..
