### ISSUE TITLE
Allow to set values in DSF

### ISSUE THREAD

**Issue by schollii** [Praqma/helmsman#40]
I notice that currently, the .set node supports overriding properties defined in the values files, but using only environment variables as values. I`d like to propose that values should not be limited to environment variables. It seems like there are only a few lines of code that would be affected: 

- https://github.com/Praqma/helmsman/blob/4c7dd44e27e6f5ea57c3e9350b82897287908204/release.go#L56: this would probably be replaced with only a check that if something starts with a $, then the env var must exist.
- https://github.com/Praqma/helmsman/blob/10f3c65c6c5ea0563dec4374f6973f5a142ef248/decision_maker.go#L285: this would check that if values starts with a $ sign, then assume the rest is an env var value (get it as code does now etc), else the values is given verbatim to the command (not sure if it would need quotes added). 
- there might be tests to fix

I could try to do this if you`re in favor of this feature, but it might be faster for you to do it, not sure.

**Comment by sami-alajrami** [comment]
thanks @schollii .. this came up before and I had intended to fix it but didn't get to it .. I will see if I can do it this week :)

**Comment by sami-alajrami** [comment]
this is shipped in v1.3.0-rc :)

**Comment by krogon** [comment]
@sami-alajrami To be fairly I do not like this approach. This limits the possibility to set value of any variable with "restricted" keywords (popular env variables names: `TERM`, `SHELL`, `USER`, `HOME`, `DISPLAY`, `_`).

**Comment by sami-alajrami** [comment]
Good point @krogon .. I will look into it

**Comment by luisdavim** [comment]
@krogon do you think that #79 addresses your cases? if you need to use those, you can set them in the `.env` file and those will only be used in `helmsman` context.

**Comment by luisdavim** [comment]
I was looking into this and there are two functions to expand environment variables. One in `state.go` `envVarExists` and one in `utils.go` `envVarExists` should we consolidate that?

**Comment by sami-alajrami** [comment]
@luisdavim yes, these should be consolidated.

**Comment by luisdavim** [comment]
I'll try to address this in #79

**Comment by luisdavim** [comment]
Done and now it does expand strings like `STRING-$VARIABLENAME-STRING`.
