### ISSUE TITLE
Ability to know the release context by command line

### ISSUE THREAD

**Issue by galindro** [Praqma/helmsman#401]
I'm getting this error after I type Ctrl+C in the middle of a release deployment:

```bash
2020-01-30 13:09:53 CRITICAL: Release [ victoria-metrics-single ] in namespace [ monitoring ] already exists but is not managed by the current context: [ services ]. Applying changes will likely cause conflicts. Change the release name or namespace.
```

How can I know what is the current release context? Would be nice if helmsman informs it and gives us the ability to change it...

**Comment by galindro** [comment]
Might be related to https://github.com/helm/helm/issues/7139#issuecomment-580244321

**Comment by luisdavim** [comment]
Helmsman labels the releases that it manages, if the helm release doesn't have it's labels Helmsman will consider it out of context. The problem is that helm now clears the labels every time and Helmsman only puts them back at the end, if you interrupted the process the labels might be missing....

**Comment by luisdavim** [comment]
You can manually label the helm secret corresponding to that release to have Helmsman "adopt" it, you can find the labels here https://github.com/Praqma/helmsman/blob/5fe70ad5e2f5abafa7691e7fa50554c852e3597e/internal/app/release.go#L355 or just look at the labels of any other helm release being managed by Helmsman.
