### ISSUE TITLE
Support for kustomize

### ISSUE THREAD

**Issue by sheerun** [Praqma/helmsman#414]
Maybe it would be good idea to integrate with kustomize so it's possible to change used charts without forking them? https://github.com/kubernetes-sigs/kustomize 

The kustomization.yaml could be a part of per-app helmsman config

**Comment by luisdavim** [comment]
and you'd suggest we'd install the helmcharts with `helm template` then run `kustomize` and finally `kubectl apply`? We'd be  loosing some of the features provided by helm or is there another way of using `kustomize` with helm?

**Comment by sheerun** [comment]
You can use kustomize as `--post-renderer` without loosing any features https://helm.sh/docs/topics/advanced/

**Comment by kferrone** [comment]
Oh wow thanks a ton @sheerun 
I'v been looking for an example like that. 
This would be a very useful feature.

**Comment by luisdavim** [comment]
That's cool, I didn't knew helm supported that. Thanks.

**Comment by luisdavim** [comment]
Can you try using the `helmFlags` option @kferrone mentioned and letting us know if it worked or if we need to make any changes to make it work?

**Comment by kferrone** [comment]
@luisdavim  @sheerun 

Holy friggin smokes it worked like a charm!! 😂

`./helmsman.yaml`
```yaml
helmFlags: [
    "--post-renderer", 
    "./kustomize/kustomize.sh"
]
```

`./kustomize/kustomize.sh`
```bash
#!/bin/bash

cat <&0 > ./kustomize/all.yaml

kustomize build ./kustomize && rm ./kustomize/all.yaml
```

`./kustomize/kustomization.yaml`
```yaml
resources:
  - all.yaml
commonLabels:
  organization: praqma
```

To really get your kustomize game on set the following variable: 
`export PLUGIN_ROOT="./kustomize/plugins"`

Then make some kustomization plugins!

Happy Helming!!

**Comment by sheerun** [comment]
helmFlags could would but I would really appreciate if it was possible to configure kustomize directly in per-app helmsman config (maybe also some global one)

**Comment by kferrone** [comment]
I feel this feature request and #360 can be merged into one feature which simply utilizes kustomize. 
I delve deeper in a comment on #360 as to what I am imagining. 

@sheerun [Please read my comment](https://github.com/Praqma/helmsman/issues/360#issuecomment-597959093) and chime in with anything else you imagine.

**Comment by luisdavim** [comment]
closed via https://github.com/Praqma/helmsman/pull/516
