### ISSUE TITLE
Namespaces aren't updated

### ISSUE THREAD

**Issue by galindro** [Praqma/helmsman#417]
I figured out that if we remove annotations from namespaces in DSL, helmsmen doesn't deletes them from kubernetes.

**Comment by sami-alajrami** [comment]
yes, namespace management has been create and update only. Removing limits, annotations, or the namespaces themselves does not cause Helmsman to delete them. 

The tricky part to make deletion happens is that Helmsman does not maintain any state files. For helm releases, Helmsman adds small state info in labels added to the secerts/configmaps used by Helm. 

We might need to do the same for namespaces. It must track any labels, annotations and limits in addition to the namespaces created by Helmsman. The tricky part would be to track individual labels and annotations when you no longer have them in the DSF and remove those.
