### ISSUE TITLE
JSON Schema for Helmsman Yaml

### ISSUE THREAD

**Issue by kferrone** [Praqma/helmsman#419]
Would be really nice to have a json-schema for the yaml files. 
Then in vscode:
```json
"yaml.schemas": {
        "https://raw.githubusercontent.com/Praqma/helmsman/master/schema/helmsman.schema.json": "helmsman.yaml"
    }
```

Sugar is good!

**Comment by luisdavim** [comment]
I like the idea and I also think we should make the `helmsman` structs available in a `go` package so they can be imported by other tools.

**Comment by luisdavim** [comment]
Maybe we can use something like https://github.com/alecthomas/jsonschema
