### ISSUE TITLE
Long arg names should require double dash

### ISSUE THREAD

**Issue by schollii** [Praqma/helmsman#42]
Only single-letter command line arg names should have a single dash; arg names with more than one letter, like `debug` and `apply`, should use double-dash, as is conventional in unix systems.

**Comment by sami-alajrami** [comment]
both long and short arg names currently work with either a single or double dashes:

both `helmsman -v` and `helmsman --v` work. Also, `helmsman -apply` and `helmsman --apply` work. 
We need to update the help output and documentation to emphasize the unix convention.

**Comment by krogon** [comment]
@sami-alajrami I think it is sufficient to replace standard `pflag` with
```go
import flag github.com/spf13/pflag
```
This is compliant with POSIX/GNU. I prefer this standard, but I am curious about backward-compatibility, as `-apply` would now mean `-a -p -p -l -y`. Any thoughts?

**Comment by schollii** [comment]
how about a few lines of code to check for backward compat args (like -apply, etc) to print deprecation warning and continue as though the double-dash had been used? This would still allow user to use **valid** aggregations of one-letter args.

**Comment by marcelloromani** [comment]
> I prefer this standard, but I am curious about backward-compatibility, as -apply would now mean -a -p -p -l -y. Any thoughts?

The BOFH in me is suggesting to silently switch to the *proper* convention and let those who foolishly didn't follow it screw themselves as they deserve it. 

_big winky face_

I think @schollii 's proposal is sensible.
