### ISSUE TITLE
Better documentation for installTiller=true

### ISSUE THREAD

**Issue by schollii** [Praqma/helmsman#43]
So far we have been using helmsman with tiller installed by default in kube-system. There are a couple of namespaces which should have their own tiller, so I'm trying to use installTiller=true for those, but I see this: 
```
Helmsman version: v1.2.0-rc2-060518
2018/06/18 19:34:27 INFO: validating that helm is installed.
2018/06/18 19:34:29 INFO: validating that kubectl is installed.
2018/06/18 19:34:30 INFO: Parsed [[ /project/helmsman.toml ]] successfully and found [ 6 ] apps.
2018/06/18 19:34:30 INFO: namespace validation -- Tiller is desired to be deployed WITHOUT TLS in namespace [ myns ]. 
2018/06/18 19:34:30 INFO: setting kubectl context to [ my-context ]
2018/06/18 19:34:30 VERBOSE: kubectl config use-context my-context
2018/06/18 19:34:30 INFO: creating namespace  myns
2018/06/18 19:34:30 VERBOSE: kubectl create namespace myns
2018/06/18 19:34:31 WARN: I could not create namespace [myns ]. It already exists. I am skipping this.
2018/06/18 19:34:31 INFO: validating that serviceaccount [ tiller ] exists in namespace [ kube-system ].
2018/06/18 19:34:31 VERBOSE: kubectl get serviceaccount tiller -n kube-system
2018/06/18 19:34:32 INFO: deploying shared Tiller on namespace [ kube-system ].
2018/06/18 19:34:32 INFO: initializing helm on the current context and upgrading Tiller on namespace [ kube-system ].
2018/06/18 19:34:32 VERBOSE: helm init --upgrade --service-account tiller --tiller-namespace kube-system --override 'spec.template.spec.containers[0].command'='{/tiller,--storage=secret}'
2018/06/18 19:34:35 INFO: deploying Tiller on namespace [ myns ].
2018/06/18 19:34:35 INFO: initializing helm on the current context and upgrading Tiller on namespace [ myns ].
2018/06/18 19:34:35 VERBOSE: helm init --upgrade --service-account tiller --tiller-namespace myns --override 'spec.template.spec.containers[0].command'='{/tiller,--storage=secret}'
2018/06/18 19:34:36 INFO: checking if helm Tiller is ready in namespace [ myns ].
2018/06/18 19:34:36 VERBOSE: helm list --tiller-namespace myns
2018/06/18 19:34:36 INFO: waiting for helm Tiller to be ready ...
2018/06/18 19:34:41 INFO: checking if helm Tiller is ready in namespace [ myns ].
2018/06/18 19:34:41 VERBOSE: helm list --tiller-namespace myns
2018/06/18 19:34:42 INFO: waiting for helm Tiller to be ready ...
2018/06/18 19:34:47 INFO: checking if helm Tiller is ready in namespace [ myns ].
2018/06/18 19:34:47 VERBOSE: helm list --tiller-namespace myns
<... keeps doing this until it eventually gives up...>
```
It seems to me that I need to setup RBAC for myns, as described in https://github.com/kubernetes/helm/blob/master/docs/rbac.md? If that is correct, there probably should be a reference to this in https://github.com/Praqma/helmsman/blob/master/docs/how_to/multitenant_clusters_guide.md, perhaps a short explanation of why this is not handled automatically by helmsman.

**Comment by krogon** [comment]
https://github.com/Praqma/helmsman/blob/a6a2c9fe24587872e01ac7c56dc7e1787f904f79/docs/desired_state_specification.md#settings

> serviceAccount: the name of the service account to use to initiate helm. This should have enough permissions to allow Helm to work and should exist already in the cluster. More details can be found in [helm's RBAC guide](https://github.com/kubernetes/helm/blob/master/docs/rbac.md)

**Comment by schollii** [comment]
This reference is in a completely different section of the documentation. For people relatively new to helm/tiller/helmsman, this stuff is not obvious.

**Comment by sami-alajrami** [comment]
since you don't specify a service account for namespace `myns` , it is falling back to use the one you specify in the settings section (in that case it appears to be called `tiller`). Currently, this should exist before in `myns`and that's why Tiller never becomes ready in that namespace. 

In addition to the documentation, I see two issues : 
1) Helmsman checks if the service account exists or not for the kube-system Tiller : 
 ```
2018/06/18 19:34:31 INFO: validating that serviceaccount [ tiller ] exists in namespace [ kube-system ].
```
But it does not do this check for other namespaces! 
2) As you suggested, Helmsman could (should) create the necessary service accounts if they don't exist.
