### ISSUE TITLE
 dry-run flag does not suppress chart yaml and other user supplied values

### ISSUE THREAD

**Issue by mam8270** [Praqma/helmsman#432]
Helmsman dry-run flag will print out USER-SUPPLIED VALUES variables  and the entire chart yaml, which may include  secrets (even when the --debug flag is disabled). I am looking for an option to run the dry-run option but with the chart and and rendered values suppressed . This is the behavior that is observed  when deploying without the dry-run flag. 

 If this feature exists, let me know.

**Comment by sami-alajrami** [comment]
Hi @mam8270 , helmsman dry-run flag simply translates into helm --dry-run flag. The helm dry-run outputs the rendered templates and use values to stdout. On the helmsman side, we can block that output but then the dry-run option becomes kind of pointless. So unfortunately, there is not much we can do about this from helmsman's side.

I will close this, but if you have more thoughts or ideas about how to overcome this, feel free to reopen.
