### ISSUE TITLE
Include another Helmsman File

### ISSUE THREAD

**Issue by kferrone** [Praqma/helmsman#436]
I would like to include other helmsman file in the main file instead of just through the `-f helmsman.yaml` option.  Is this already possible by chance? This way I would not need to pass so many flags to the command and there would be one file to rule them all. Also it would add some clarity when reading the file that other files are indeed a part of it. 

I imagine something like this:
```yaml
includes:
  - other/services/helmsman.yaml
  - ${ENV}/helmsman.yaml
```

**Comment by orefalo** [comment]
that would be cool, next would be to parametrize those yaml.
