### ISSUE TITLE
valuesFile is not supporting absolute path

### ISSUE THREAD

**Issue by james-r-smith** [Praqma/helmsman#437]
I have a desired state file, where I specify `valuesFile` with `/values/{values file}.yaml`. (running inside a container) I have my desired state in a separate directory, `/manifests`. When I run the following statement: `helmsman -f /manifests/desired-state.yml --debug --dry-run`, I am getting the following error:

```
2020-04-16 19:23:27 CRITICAL: open /manifests/values/{values file}.yaml: no such file or directory
```

It appears Helmsman (v3.1.0) is doing relative path, and not absolute despite specifying an absolute path.

**Comment by sami-alajrami** [comment]
Hi @james-r-smith . Indeed, helmsman resolves file paths relatively from the location of the desired state file and replaces the relative paths with generated absolute paths at runtime. 

I will add a check to allow absolute paths.
