### ISSUE TITLE
Feature request - Run shell command

### ISSUE THREAD

**Issue by orefalo** [Praqma/helmsman#446]
Really like this tool, it helps a lot. With that said, it's missing a key capability:

The ability to run shell command.  The command should know in which context it is running (apply/destroy)

Typical use cases include:

1. Sleep X seconds - that's when wait in not enough
2. Deploy kubectl yaml without the need to create a helm container project
3. Add/Remove CRD definitions, ie:
for n in $(kubectl get namespaces -o jsonpath={..metadata.name}); do
  kubectl delete --all --namespace=$n prometheus,servicemonitor,podmonitor,alertmanager
done

Thank you

**Comment by sami-alajrami** [comment]
#421 addresses 1 and 2 and to some extent 3. It will allow applying k8s yaml manifests before/after helmsman operations. These manifests can be a pod which sleeps for sometime, a CRD installation or any other k8s object. 
The reason for not supporting arbitrary shell commands is that it's not easily possible to revert their effect which will make the operations of helmsman non-idempotent. 
I will try to finalize that PR sometime this week and merge it.

**Comment by orefalo** [comment]
thank you , closing.

Stay safe,
Sincerely
