### ISSUE TITLE
feature request: configuration file for helmsman

### ISSUE THREAD

**Issue by rasta-rocket** [Praqma/helmsman#447]
Hello folks,

So the idea would be basically to have a configuration file that could contains all or part of the options that we can use today with the helmsman binary.

Example: Let's assume that I always want to disable the env variables substitution which is enabled by default. I would have a config file that I can share with others and it will simplify the use of the binary when applying stuff: less options on the command line and standard options located in a central file.

The config file should be found in known locations (etc directory, home directory, current directory). The options set up inside that file should be less prioritized then environment variables or options in CLI form.

Cheers

**Comment by orefalo** [comment]
I personally find this feature error prone.

The configuration today lives in the helmsman.yaml file, defaulting to a master configuration may lead to unexpected behaviors.

My 2c
