### ISSUE TITLE
helm flags are not passed to `helm diff upgrade` command

### ISSUE THREAD

**Issue by mehyedes** [Praqma/helmsman#451]
We are using the `helmFlags` option to pass the `--set-file` flag to one of our apps as follows:
```
helmFlags = [
         "--set-file",
         "db_seeds=values/seeds/seeds.rb",
         "--set-file",
         "events_config=values/seeds/events.yaml",
]
```
However, I have noticed that these flags are not passed to `helm-diff` when doing an upgrade.
Which causes receive the error below:
```
[35m2020-05-07 15:39:10 CRITICAL: Command returned with exit code: 1. And error message: Error: Failed to render chart: exit status 1: Error: template: banking-backend/templates/configmap-seed.yaml:11:29: executing "banking-backend/templates/configmap-seed.yaml" at <4>: invalid value; expected string
```
I was able to reproduce the issue with `helm diff` if I don't pass the `--set-file` option.
I see here that `r.getHelmFlags()` only passed to the install command:

https://github.com/Praqma/helmsman/blob/f18616fee18a0cf16bef04071208587407f085f6/internal/app/release.go#L497-L506

I know `--set-file` is now supported with https://github.com/Praqma/helmsman/pull/444 so we can use the `setFile` stanza, but I just wanted ask if there was a reason behind that, like maybe to prevent certain flags from being passed to the upgrade command?

**Comment by sami-alajrami** [comment]
thanks @mehyedes .. I am not aware of a reason flags shouldn't be passed to the upgrade and diff commands. I will label as a bug.

**Comment by sami-alajrami** [comment]
After digging a bit further, `getHelmArgsFor()` can't be added to the helm diff call because of high possibility of incompatible/unsupported flags. Therefore, it is not recommended to use `helmFlags` for setting values. Instead, use `set`, `setString` or `setFile` which will be passed to the helm diff call.

**Comment by mehyedes** [comment]
Thanks for looking into this @sami-alajrami . That was what I had initially expected. 

Waiting for the next release to have `setFile` 👍
