### ISSUE TITLE
Use --purge when deleting charts

### ISSUE THREAD

**Issue by flypenguin** [Praqma/helmsman#46]
**Steps to reproduce**

1. install a chart (using helm from the command line)
1. add the chart's config into a helmsman file, set `enabled: false` (or omit it, currently)
1. run `helmsman -apply` (the chart should be deleted, see appendix I below)
1. add `enabled: true` to the chart
1. run run `helmsman -apply` again

**Expected result::**

The chart should be re-deployed

**Actual result:**

An error message (see Appendix II below) with a weird "exit code" character. Might be my fonts are not configured, but I guess there should be a number ... :)

**Steps to manually fix this:**

`helm delete --purge nginx-ingress-ext`. After that a re-run of `helmsman -apply` just works.

**Metadata**

* Helmsman version: `1.3.0-rc1`

**Appendix I**

The deletion of the chart by helmsman:

```
2018/07/12 13:45:25 INFO: Plan generated at: Thu Jul 12 2018 13:45:25 
DECISION: release [ nginx-ingress-ext ] is desired to be deleted . Planing this for you! -- priority: 0
2018/07/12 13:45:25 INFO: sorting the commands in the plan based on priorities (order flags) ... 
2018/07/12 13:45:25 INFO: Executing the following plan ... 
----------------------
2018/07/12 13:45:25 INFO: Plan generated at: Thu Jul 12 2018 13:45:25 
DECISION: release [ nginx-ingress-ext ] is desired to be deleted . Planing this for you! -- priority: 0
```

**Appendix II**

The error message:

```
2018/07/12 13:46:16 INFO: Plan generated at: Thu Jul 12 2018 13:46:15 
DECISION: release [ nginx-ingress-ext ] is currently deleted and is desired to be rolledback to namespace [[ kube-system ]] . It will also be upgraded in case values have changed. -- priority: 0
2018/07/12 13:46:16 INFO: sorting the commands in the plan based on priorities (order flags) ... 
2018/07/12 13:46:16 INFO: Executing the following plan ... 
----------------------
2018/07/12 13:46:16 INFO: Plan generated at: Thu Jul 12 2018 13:46:15 
DECISION: release [ nginx-ingress-ext ] is currently deleted and is desired to be rolledback to namespace [[ kube-system ]] . It will also be upgraded in case values have changed. -- priority: 0
2018/07/12 13:46:17 Command returned with exit code: . And error message: Error: "nginx-ingress-ext" has no deployed releases
```

**Comment by sami-alajrami** [comment]
@flypenguin I guess your helmsman config  didn't have the `purge` option set to true.  See [here](https://github.com/Praqma/helmsman/blob/master/docs/desired_state_specification.md#apps) for details. As a result, helmsman just deleted your release without "purging" it. 

When you enable the chart and deploy again, it's trying to rollback the deleted release : 
```
DECISION: release [ nginx-ingress-ext ] is currently deleted and is desired to be rolledback to namespace [[ kube-system ]] . It will also be upgraded in case values have changed. -- priority: 0
```
Ideally, this should rollback your nginx to the latest helm revision. But this is failing and the error you are seeing `Error: "nginx-ingress-ext" has no deployed releases` is coming from helm.  

What version of Helm are you using? helm v2.8.2 and above has a [bug](https://github.com/kubernetes/helm/issues/3722) that prevents rollaback of deleted releases from working. 

Could you install the same chart with helm from command line, delete it (without purge) and redeploy again from command line? does it work?

**Comment by flypenguin** [comment]
okay, it could be the helm but - I'm using v2.9.1. let me try your approach to get more clarity.

**Comment by sami-alajrami** [comment]
v2.9.1 has the bug I mentioned above .. if you fall back to v2.8.1, rollback will work. If you are not interested in rollback, then just set the purge option to true :)

**Comment by flypenguin** [comment]
oh cool, so this can be closed :)

Am Do., 12. Juli 2018 um 15:54 Uhr schrieb Sami Alajrami <
notifications@github.com>:
