### ISSUE TITLE
How to pass Helm values file to docker container

### ISSUE THREAD

**Issue by nitin-ag** [Praqma/helmsman#461]
Hello,

We are using helm charts to run Kubernetes one off jobs and as part of that it attempts to apply some of the database seed available in one of the published/available docker image. The seed yaml file contains the reference to the customNamespace (namespace: {{ .Values.customNamespace }}) and the referenced property is available in values.yaml of helm chart.

However as at docker container level we just doing kc apply , it is not able to resolve the referenced property from helm and the job fails with the below error -

error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.customNamespace ":interface {}(nil)}

Wondering if there is a way for us to pass the helm chart value to the docker container ?
Any suggestions are greatly appreciated.

**Comment by sami-alajrami** [comment]
Hi @nitin-ag this is a helm question not helmsman :)
It is not clear what you are trying to achieve, but assuming the docker container you are talking about is helmsman container, you can pull your source code inside the container and define the release in your desired state file which points to your values file. See [this the desired state spec](https://github.com/Praqma/helmsman/blob/master/docs/desired_state_specification.md#apps) for details, and the [examples](https://github.com/Praqma/helmsman/tree/master/examples).
