### ISSUE TITLE
Helms secrets not working in 3.4.0

### ISSUE THREAD

**Issue by mehyedes** [Praqma/helmsman#468]
Seems like the integration with helm secrets is broken in the latest release `3.4.0`.
Whenever I try to deploy this app with helmsman
```
  [apps.demo-app]
    name = "demo-app"
    description = "Demo App"
    namespace = "default"
    enabled = true
    chart = "chartmuseum/demo-app"
    version = "0.0.2"
    valuesFile = "values/demo-app.yaml"
    secretsFile = "secrets/demo-app/secrets.yaml"
    timeout = 600
```
I get the same error below:
```
2020-05-14 18:58:31 CRITICAL: Error unmarshaling input YAML: yaml: line 27: could not find expected ':'
Error: plugin "secrets" exited with error
```
Using the `helm secrets` command directly works fine though.
```
helm secrets upgrade demo-app chartmuseum/demo-app --install -f deploy/values/demo-app.yaml -f deploy/secrets/demo-app/secrets.yaml
```
Might be a side effect of https://github.com/Praqma/helmsman/pull/458, but I am just guessing here.

Please note that this was working fine with `3.3.0`

**Comment by ndegory** [comment]
or maybe a side effect of #469 if you have multiple apps with a secrets.yaml file

**Comment by mehyedes** [comment]
I was only guessing, did not really dive into the code.
I will test your fix with the latest master.
Thanks @ndegory

**Comment by mehyedes** [comment]
**Update:** I can confirm https://github.com/Praqma/helmsman/pull/470 fixes this issue.
