### ISSUE TITLE
can not use --devel helmsFlag

### ISSUE THREAD

**Issue by gangadharmgithub** [Praqma/helmsman#480]
helm install -h
....
**--devel                        use development versions, too. Equivalent to version '>0.0.0-0'. If --version is set, this is ignored**

I used to install the chart with '--devel'  without specifying the version of the chart and it used to pick up the latest chart available in the helm repo. 

**helmsman made the version as a mandatory field, effectively I can not use the --devel helm option.**

$helmsman -e values/env_prod -f helmsman.yaml -subst-env-values -apply 
2020-05-28 17:04:55 INFO: Parsed YAML [[ helmsman.yaml ]] successfully and found [ 1 ] apps
2020-05-28 17:04:55 INFO: Validating desired state definition...
2020-05-28 17:04:55 CRITICAL: apps validation failed -- for app [cert-manager ]. version can't be empty

helmsman.yaml
----------------------
metadata:
  org: Test Inc

context: test

helmRepos:
  jetstack: https://charts.jetstack.io
  

namespaces:
  $NAMESPACE:

appsTemplates:
  default: &template
    namespace: $NAMESPACE
    valuesFile: ""
    helmFlags: [ "--devel"]
    protected: false
    wait: true
    enabled: true
    group: akriapps

apps:
  cert-manager:
    <<: *template
    chart: jetstack/cert-manager
    #version: v0.13.0
    priority: -100

**Comment by sami-alajrami** [comment]
what version of helmsman are you using?

**Comment by gangadharmgithub** [comment]
> what version of helmsman are you using?
version: v3.4.0

**Comment by mkubaczyk** [comment]
Unfortunately, Helmsman requires version to be passed as of now, which is a part of chart's validation here https://github.com/Praqma/helmsman/blob/master/internal/app/release.go#L85. There's many places that rely on the version now so this is lots of changes needed
