### ISSUE TITLE
`panic: runtime error` when deleting an untracked release

### ISSUE THREAD

**Issue by pmichna** [Praqma/helmsman#481]
## Helm and Helmsman versions
```
$ helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

$ helmsman version

 _          _
| |        | |
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | |
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v3.4.2
A Helm-Charts-as-Code tool.
```

## Steps to reproduce
1. Create `helmsman.toml` file:
```
context = "pablo"

[settings]
  kubeContext = "minikube"

[namespaces]
  [namespaces.kube-system]
  [namespaces.pablo]

[helmRepos]
  stable = "https://kubernetes-charts.storage.googleapis.com"
  bitnami = "https://charts.bitnami.com/bitnami"

[apps]
  [apps.apache]
    namespace   = "pablo"
    chart       = "bitnami/apache"
    version     = "7.3.16"
    name        = "apache"
    enabled     = true
```

2. Run `helmsman -apply -verbose -f helmsman.toml`
3. Remove the `[apps.apache]` section from `helmsman.toml`.
4. Run `helmsman -apply -verbose -f helmsman.toml` again.
5. the following error happens:

```
[...]
2020-05-29 08:55:36 NOTICE: -------- PLAN starts here --------------
2020-05-29 08:55:36 WARNING: Untracked release [ apache ] found and it will be deleted -- priority: -1000
2020-05-29 08:55:36 NOTICE: -------- PLAN ends here --------------
2020-05-29 08:55:36 INFO: Sorting the commands in the plan based on priorities (order flags) ...
2020-05-29 08:55:36 INFO: Executing plan...
2020-05-29 08:55:36 INFO: Plan applied
2020-05-29 08:55:36 INFO: Cleaning up sensitive and temp files
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18c8e9c]

goroutine 44 [running]:
github.com/Praqma/helmsman/internal/app.(*plan).exec.func1(0xc00038c340, 0xc0003ea180, 0x1b1e355, 0x4, 0xc0003b8240, 0x4, 0x4, 0xc000394bc0, 0x3a, 0xfffffffffffffce0, ...)
	github.com/Praqma/helmsman/internal/app/plan.go:119 +0x15c
created by github.com/Praqma/helmsman/internal/app.(*plan).exec
	github.com/Praqma/helmsman/internal/app/plan.go:111 +0x4e2
```

I've been able to reproduce the above both on minikube and EKS using different charts.

**Comment by ppandiya** [comment]
Facing the same issue.

`2020-06-02 12:57:44 NOTICE: -------- PLAN ends here --------------
2020-06-02 12:57:44 INFO: Executing plan...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcc3fdc]

goroutine 140 [running]:
github.com/Praqma/helmsman/internal/app.(*plan).exec.func1(0xc0004c4620, 0xc0000824e0, 0xf18156, 0x4, 0xc0000b4780, 0x6, 0x8, 0xc00019e2d0, 0x48, 0xfffffffffffffce0, ...)
	/go/src/github.com/Praqma/helmsman/internal/app/plan.go:119 +0x15c
created by github.com/Praqma/helmsman/internal/app.(*plan).exec
	/go/src/github.com/Praqma/helmsman/internal/app/plan.go:111 +0x4e2
[jenkins@ip-10-30-110-175 app2-perf]$ helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}`

**Comment by markruler** [comment]
Same issue.

Helmsman version: v3.4.2

> Case 1
1. Run `helmsman -apply -f app1.toml` => success
2. Run `helmsman -apply -f app2.toml` => panic

> Case 2
1. Run `helmsman -apply -f app2.toml` => success
2. Run `helmsman -apply -f app1.toml` => panic

**Comment by markruler** [comment]
I think you should run this command `helm uninstall apache --namespace pablo` first, then run helmsman.

**Comment by pmichna** [comment]
@markruler I could but Helmsman should do it too when not using the `--keep-untracked-releases` option.

**Comment by pmjacinto** [comment]
there seems to be a missing null check [here]( https://github.com/Praqma/helmsman/blob/master/internal/app/plan.go#L117) as uninstall commands have `targetRelease` set to nil: https://github.com/Praqma/helmsman/blob/master/internal/app/helm_release.go#L87

**Comment by mkubaczyk** [comment]
#489 should fix that. I believe this bug was introduced with hooks recently :-)
