### ISSUE TITLE
Helmsman support for Helm 3.2.x

### ISSUE THREAD

**Issue by Wobbley** [Praqma/helmsman#482]
Do you have a timeline on when you will use helm 3.2.x? Asking specifically due to this PR: https://github.com/helm/helm/pull/7649

It addresses issues helm has with upgrading and changing deprecated APIs on resources while avoiding downtime.

**Comment by sami-alajrami** [comment]
Hi @Wobbley helmsman v3.4.0 [docker images](https://hub.docker.com/repository/docker/praqma/helmsman/tags?page=1) and after are published with helm v3.2.1 as an option.

**Comment by sami-alajrami** [comment]
if you are using the Helmsman binary, it should work with helm v3.2.x

**Comment by andrelin** [comment]
Hey @sami-alajrami 
I'm a colleague of @Wobbley and I've been trying to build a docker image from praqma/helmsman:v3.4.2-helm-v3.2.1 but this happens, I end up with Helm 3.1.1 and not 3.2.1

`Step 1/23 : FROM praqma/helmsman:v3.4.2-helm-v3.2.1
 ---> b3ef50e47404

Step 2/23 : RUN helm version
 ---> Running in 48b129552040
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
 `

**Comment by andrelin** [comment]
I have no tried this with `praqma/helmsman:v3.4.1-helm-v3.2.1` and with `praqma/helmsman:v3.4.0-helm-v3.2.1` with the same result

```
Sending build context to Docker daemon  4.872MB
Step 1/2 : FROM praqma/helmsman:v3.4.1-helm-v3.2.1
v3.4.1-helm-v3.2.1: Pulling from praqma/helmsman
cbdbe7a5bc2a: Already exists
7b9d684fce8f: Pull complete
6ec31ee81f55: Pull complete
ac9cba4c8c49: Pull complete
Digest: sha256:cfc0a0c05a1bed2af4e061b5022aea90d3d3d0d6769f9f5667b241f2e519f3e7
Status: Downloaded newer image for praqma/helmsman:v3.4.1-helm-v3.2.1
 ---> 42268ff7f3df
Step 2/2 : RUN helm version
 ---> Running in a00d5e92119a
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
Removing intermediate container a00d5e92119a
 ---> c04cae1b659d
Successfully built c04cae1b659d
```
---
```
Sending build context to Docker daemon  4.872MB
Step 1/2 : FROM praqma/helmsman:v3.4.0-helm-v3.2.1
v3.4.0-helm-v3.2.1: Pulling from praqma/helmsman
cbdbe7a5bc2a: Already exists
6b6ed4df6573: Pull complete
0c10ab6fc18b: Pull complete
2055aea70fcf: Pull complete
Digest: sha256:c17fe173a55f6c34d12b9fc55364a2c2ccd9225e6db6eb0874f8ba1a94c2795a
Status: Downloaded newer image for praqma/helmsman:v3.4.0-helm-v3.2.1
 ---> 68d4050d6730
Step 2/2 : RUN helm version
 ---> Running in 7b5fb66e5298
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
Removing intermediate container 7b5fb66e5298
 ---> 830264493f3e
Successfully built 830264493f3e
```

**Comment by andrelin** [comment]
@sami-alajrami Why did you close this? The images doesn't seem to work as intended.

**Comment by sami-alajrami** [comment]
apologies @andrelin this was a bug in the release script where the helm version was not correctly passed. The bug is fixed in commit 965a25b (thus the closure of the issue).
I am fixing the following images manually and pushing them to dockerhub. They should all have helm v3.2.1 shortly.

```
praqma/helmsman:v3.4.0-helm-v3.2.1 (rebuilding)
praqma/helmsman:v3.4.1-helm-v3.2.1 (rebuilding)
praqma/helmsman:v3.4.2-helm-v3.2.1 (pushed)
```

**Comment by andrelin** [comment]
Thank you
I have tested that `praqma/helmsman:v3.4.2-helm-v3.2.1` does have the correct helm version now.

**Comment by sami-alajrami** [comment]
all the images above are now pushed!
