### ISSUE TITLE
helmsman can not be used with development versions

### ISSUE THREAD

**Issue by gangadharmgithub** [Praqma/helmsman#485]
$ helmsman version

 _          _ 
| |        | | 
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \ 
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | | 
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v3.4.0
A Helm-Charts-as-Code tool.

2020-06-03 18:49:36 INFO: No desired state files provided.
$ helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

I have helm repo with development version like

helm repo list
cloudserver-chart    	s3://test-charts/charts/cloudserver/1.9.1-SNAPSHOT

It has a chart with the name: cloudserver-1.9.1-SANPSHOT-719.tgz

The DSF is: 
-----

metadata:
  org: Test Inc

context: test_internalapps_1.9.1

preconfiguredHelmRepos:
  - cloudserver-chart

namespaces: 
  $NAMESPACE:

appsTemplates:
  default: &template
    namespace: $NAMESPACE
    valuesFile: ""
    **helmFlags: [ "--devel"]**
    protected: false
    enabled: true
    group: akriapps

apps:
  cloudserver:
    <<: *template
    chart: cloudserver-chart/cloudserver
    priority: ${CLOUDSVC_PRI}
    version: ${CLOUDSERVER_CHART_VERSION}
    valuesFile: "${CONFIG_BASEDIR}/cloudserver/cloudserver-values.yaml"

-------

While installing this chart got an error:

**2020-06-03 18:33:36 DEBUG: helm show chart cloudserver-chart/cloudserver
2020-06-03 18:33:36 CRITICAL: While getting chart information: Error: failed to download "cloudserver-chart/cloudserver" (hint: running `helm repo update` may help)**

**"helm show chart cloudserver-chart/cloudserver" is not using the --devel flag.**  

 helm show chart cloudserver-chart/cloudserver --devel
apiVersion: v2
appVersion: 1.9.1-SNAPSHOT-719
description: A Helm chart for Cloud Server deployment on Kubernetes.
name: cloudserver
type: application
version: 1.9.1-SNAPSHOT-719
 
I can not see any workaround to fix this issue.  Looking for alternative tools.  I need to check if **helmsfile** addresses the development versions and honors --devel flag.

**Comment by pmjacinto** [comment]
I believe this should work in 3.4.1, despite it being broken again in 3.4.2

see: https://github.com/Praqma/helmsman/issues/456

**Comment by ml-** [comment]
Late to the party, still wanna chip in:

Using devel versions in general works. I've been using it for quite a while now.
The version format I know works is: `1.2.3-rc1`.

You don't even need to pass the `--devel` flag.

**Comment by jasmdk** [comment]
We have the same issue. It seems to work if there is at least one version which is not a develop version. During the execution it invokes 'helm show chart <repo>/<chart-name>' which will show the latest version if there is no version constraint and in our case this will not find the chart and suggest to update repo. However if we apply the version with '--version <some-develop-version>' it works. It seems like version 3.4.1 uses 'show' with version constraint, but later builds do not.

**Comment by erpel** [comment]
Still an issue with 
helm version
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"dirty", GoVersion:"go1.15.3"}

helmsman version: v3.4.6
A Helm-Charts-as-Code tool.

**Comment by antoinedeschenes** [comment]
Still an issue with 3.6.2? All the `helm show chart`  calls were refactored
