### ISSUE TITLE
Bug: unable to recover from a failed upgrade/install when context is used in DSF

### ISSUE THREAD

**Issue by gangadharmgithub** [Praqma/helmsman#492]
Helsmman version: version: v3.4.0
Helm version: 3.2.1

**Steps to reproduce the issue**
*   DSF and values files

test_minio.yaml
```
context: test_context
helmRepos:
  stable: https://kubernetes-charts.storage.googleapis.com
namespaces: 
  test:

appsTemplates:
  default: &template
    namespace: test 
    valuesFile: ""
    helmFlags: [ "--devel", "--debug"]
    protected: false
    enabled: true

apps:
  minio:
    <<: *template
    chart: stable/minio
    version: 5.0.20
    valuesFile: "miniovalues.yaml"
    wait: true
```
miniovalues.yaml
```
mode: distributed
accessKey: testAkey 
secretKey: testSkey 
DeploymentUpdate:
  maxUnavailable: 1
persistence:
  size: 1Gi 
buckets:
  - name: test-bucket 
    policy: none
    purge: false

```

Apply the DSF

```
$ helmsman -f test_minio.yaml -apply
....
2020-06-10 11:54:29 NOTICE: Finished: Install release [ minio ] version [ 5.0.20 ] in namespace [ test ]
```

* Modify the DSF with a timeout of 1sec to trigger an upgrade failure (failure can be possible due to network issues)

test_minio.yaml
```
context: test_context
helmRepos:
  stable: https://kubernetes-charts.storage.googleapis.com
namespaces: 
  test:

appsTemplates:
  default: &template
    namespace: test 
    valuesFile: ""
    helmFlags: [ "--devel", "--debug"]
    protected: false
    enabled: true

apps:
  minio:
    <<: *template
    chart: stable/minio
    version: 5.0.20
    valuesFile: "miniovalues.yaml"
    wait: true
    timeout: 1
```

```
$ helmsman -f test_minio.yaml -apply
....
Error: UPGRADE FAILED: timed out waiting for the condition
```

* Removed the timeout param from the DSF file.

test_minio.yaml
```
context: test_context
helmRepos:
  stable: https://kubernetes-charts.storage.googleapis.com
namespaces: 
  test:

appsTemplates:
  default: &template
    namespace: test 
    valuesFile: ""
    helmFlags: [ "--devel", "--debug"]
    protected: false
    enabled: true

apps:
  minio:
    <<: *template
    chart: stable/minio
    version: 5.0.20
    valuesFile: "miniovalues.yaml"
    wait: true
```
```
$ helmsman -f test_minio.yaml -apply
....
**
2020-06-10 19:38:28 CRITICAL: Release [ minio ] in namespace [ test ] already exists but is not managed by the current context: [ test_context ]. Applying changes will likely cause conflicts. Change the release name or namespace.
**
```

**Issue:**  Helmsman is not able to recover from previous failures.

**Workaround:**
```
$ kubectl label secret -n test -l owner=helm,name=minio MANAGED-BY=HELMSMAN NAMESPACE=test HELMSMAN_CONTEXT=test_context
secret/sh.helm.release.v1.minio.v1 labeled
secret/sh.helm.release.v1.minio.v2 labeled
$ helmsman -f test_minio.yaml -apply
```

**Is this a known issue?**

**Comment by gangadharmgithub** [comment]
This is is an issue with install failure as well.

**Comment by sharkymcdongles** [comment]
I also encounter this and it causes great grief. Say a rolling upgrade times out then I must rerun the pipeline it will no longer work and always fail because it says "already exists but is not managed by the current context". I then label it like the other successful secrets, and it still fails the same way. The only way I can get it to work sometimes is if I delete the failed helm state secret.

Why doesn't it respect the labels when I add them? Can we possibly add a --force flag to ignore this?

**Comment by gangadharmgithub** [comment]
> I also encounter this and it causes great grief. Say a rolling upgrade times out then I must rerun the pipeline it will no longer work and always fail because it says "already exists but is not managed by the current context". I then label it like the other successful secrets, and it still fails the same way. The only way I can get it to work sometimes is if I delete the failed helm state secret.
> 
> Why doesn't it respect the labels when I add them? Can we possibly add a --force flag to ignore this?

Have you tried with --overwrite

Example: 

kubectl label secret -n test -l owner=helm,name=minio MANAGED-BY=HELMSMAN NAMESPACE=test HELMSMAN_CONTEXT=test_context --overwrite

**Comment by sharkymcdongles** [comment]
Yes I did and same result. :(

**Comment by mkubaczyk** [comment]
This might be already fixed with v3.4.4, can you please confirm?

**Comment by gangadharmgithub** [comment]
> This might be already fixed with v3.4.4, can you please confirm?

It is not fixed in v3.4.4.  You can please test using the sample test provided in the bug report.

**Comment by sami-alajrami** [comment]
This was a problem in the reported error message (not actually related to the helmsman context) and was fixed in #465 (released in v3.4.1). 
The issue happens when a release is in pending-* state. As long as the release is in some pending state, helm does not allow operating on it and therefore helmsman can't do much about it. 
The PR I mentioned only reports a more informative error message, but resolving the pending state on the release is something you need to fix according to its cause.

to verify that your releases are pending, run `helm ls -n <namespace> --all`

**Comment by moleskin-smile** [comment]
@sami-alajrami: I think this is a similar issue, but different. We use helmsman 3.4.2 and still a **failed** upgrade causes this.

I can also confirm that work around mentioned by @gangadharmgithub works. Adding these labels manually helps:

```
    HELMSMAN_CONTEXT: <context-here>
    MANAGED-BY: HELMSMAN
    NAMESPACE: <namespace-here>
```

**Comment by lastdil** [comment]
same issue at 3.4.4
