### ISSUE TITLE
Query: How to use latest version of helm-chart?

### ISSUE THREAD

**Issue by lakshaykapoor7198** [Praqma/helmsman#493]
I need my app to use the latest version of helm-chart always without explicitly defining the exact version.

As per helm install help, I should not specify version to install latest version.

> --version string           specify the exact chart version to install. If this is not specified, the latest version is installed

But if i don't specify the version in desired state file, then helmsman gives error like 

> _ERROR: apps validation failed -- for app [cogeng-relay ]. version can't be empty._

Please let me know, how i can use latest version of helm-chart without specifying the exact version?
I am using helmsman version 1.10.1 and helm client version 2.13.1.

**Comment by sami-alajrami** [comment]
Hi @lakshaykapoor7198 , Helmsman requires the chart version by design. The reason it is required is to maintain idempotency (i.e. running the same desired state multiple times should always result in the same outcome). This will be violated if the user does not specify a version explicitly.
