### ISSUE TITLE
Relation between wait and test in app state?

### ISSUE THREAD

**Issue by hazcod** [Praqma/helmsman#508]
Hi, I was wondering what the effect was of `wait: false` and `test: true` in the apps config?
Will it execute all charts and than test them all at the end?

**Comment by jamesdehart** [comment]
I was just wondering the same thing.

**Comment by jamesdehart** [comment]
@hazcod I found this [reference](https://github.com/Praqma/helmsman/commit/fbebb0344ac5b26d7e1fa06e7d87211eec85ff35#diff-300c88d51b9b5b1f8da7de5129b4a18ad19106382a161d7be3285e2e1127dd55R297)
