### ISSUE TITLE
helmsman "panic: runtime error: invalid memory address or nil pointer dereference" on any command

### ISSUE THREAD

**Issue by mortimr** [Praqma/helmsman#519]
Hi Helmsman team !

It has been 2-3 days since it started. `helmsman` is currently crashing with the following error:
```
 _          _ 
| |        | | 
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \ 
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | | 
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v3.4.4
A Helm-Charts-as-Code tool.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x51e256]

goroutine 1 [running]:
github.com/hashicorp/go-version.(*Version).Prerelease(...)
	/go/pkg/mod/github.com/hashicorp/go-version@v1.2.0/version.go:322
github.com/hashicorp/go-version.prereleaseCheck(0x0, 0xc0000cb090, 0x1)
	/go/pkg/mod/github.com/hashicorp/go-version@v1.2.0/constraint.go:118 +0x26
github.com/hashicorp/go-version.constraintGreaterThanEqual(0x0, 0xc0000cb090, 0xc0001cfbe0)
	/go/pkg/mod/github.com/hashicorp/go-version@v1.2.0/constraint.go:158 +0x35
github.com/hashicorp/go-version.(*Constraint).Check(...)
	/go/pkg/mod/github.com/hashicorp/go-version@v1.2.0/constraint.go:92
github.com/hashicorp/go-version.Constraints.Check(0xc0000aa3a8, 0x1, 0x1, 0x0, 0x1)
	/go/pkg/mod/github.com/hashicorp/go-version@v1.2.0/constraint.go:72 +0x5c
github.com/Praqma/helmsman/internal/app.(*cli).parse(0x1800460)
	/go/src/github.com/Praqma/helmsman/internal/app/cli.go:155 +0xd75
github.com/Praqma/helmsman/internal/app.init.0()
	/go/src/github.com/Praqma/helmsman/internal/app/main.go:23 +0x2d
Error: Process completed with exit code 2.
```

And this, no matter what command I use (even tried running `helmsman` without arguments to ensure it is not related to my chart/state). It happens only in Github Actions (exact same config / version / arguments on my machine works fine)

I'm currently using :
- `helmsman` 3.4.4
- `helm` 3.3.3

Any idea where this come from ? If I take a look at the stack trace, it points to a flag parsing call in the `main.go` file.

**Comment by mortimr** [comment]
To provide additional info:

This is the command I am doing to setup helmsman
```
curl -L https://github.com/Praqma/helmsman/releases/download/v3.4.1/helmsman_3.4.1_linux_amd64.tar.gz | tar zx && chmod +x helmsman && sudo mv ./helmsman /usr/local/bin/helmsman && helmsman
```

and crashes on the last command

Before this command, I configure my kubectl config with the aws cli like this
```
aws eks update-kubeconfig --name ${CONFIG_STAGING_CLUSTER_NAME} && kubectl get pod
```

(the kubectl get pod is here to ensure I have access to the cluster and the command works properly)

But now it gets weird, If I run the helmsman command before the kubectl config one, it works (but still fails whenever I call helmsman afterwards).

This is getting weird ...

**Comment by mortimr** [comment]
I found the solution for anyone struggling with this:

The `~/.kube/config` file has read & write rights for group / public groups by default. 
Helmsman was crashing because of this. By adding `chmod 600 ~/.kube/config` before using `helmsman` should fix the issue !

**Comment by oxyrox** [comment]
@mortimr IMO this is still a valid issue. Yes this is fixing the issue and yes that `chmod` should be performed.
However helmsman shouldn't panic due to a new warning printed by helm.

**Comment by mortimr** [comment]
I agree with you that helmsman crashing without any feedback is confusing. In verbose mode we see that kubectl is disaplaying a warning just before the crash happens (that's how I got the hint). 

Maybe helmsman should print stdout / stderr of a child process when it exits with an invalid status ?

**Comment by mkubaczyk** [comment]
I can't reproduce that. Every time I get
`2020-10-02 11:15:17 CRITICAL: missing information to create context [ XXX ] you are either missing PASSWORD, USERNAME or CLUSTERURI in the Settings section of your desired state file.` so there's no panic.
Please show me the output of `ls -la ~/.kube/config` when the helmsman fails. Are you sure it's the only thing you need to run before helmsman starts properly?

**Comment by mortimr** [comment]
Ok, so when running
`aws eks update-kubeconfig --name ${CONFIG_STAGING_CLUSTER_NAME} && kubectl get pod && ls -l ~/.kube`
I get
```
Added new context arn:aws:eks:***:***:cluster/*** to /home/runner/.kube/config
NAME                                       READY   STATUS    RESTARTS   AGE
cert-manager-766d5c494b-9dqxj              1/1     Running   0          20d
cert-manager-cainjector-6649bbb695-4dzrb   1/1     Running   1          20d
cert-manager-webhook-5b456ff6c-nq7jp       1/1     Running   4          63d
total 8
drwxr-x--- 4 runner docker 4096 Sep 27 13:28 cache
-rw-r--r-- 1 runner docker 2130 Sep 27 13:28 config
```

And then helmsman (with verbose mode) fails with
```
 _          _ 
| |        | | 
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \ 
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | | 
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v3.4.1
A Helm-Charts-as-Code tool.

2020-09-27 13:28:48 INFO: Checking Helm version
2020-09-27 13:28:51 INFO: Helm client version: Kubernetes configuration file is group-readable. This is insecure. Location
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x51e0e6]

goroutine 1 [running]:
github.com/hashicorp/go-version.(*Version).Prerelease(...)
	/go/pkg/mod/github.com/hashicorp/go-version@v1.2.0/version.go:322
github.com/hashicorp/go-version.prereleaseCheck(0x0, 0xc000074050, 0x1)
	/go/pkg/mod/github.com/hashicorp/go-version@v1.2.0/constraint.go:118 +0x26
github.com/hashicorp/go-version.constraintGreaterThanEqual(0x0, 0xc000074050, 0xc0000340a0)
	/go/pkg/mod/github.com/hashicorp/go-version@v1.2.0/constraint.go:158 +0x35
github.com/hashicorp/go-version.(*Constraint).Check(...)
	/go/pkg/mod/github.com/hashicorp/go-version@v1.2.0/constraint.go:92
github.com/hashicorp/go-version.Constraints.Check(0xc00000e010, 0x1, 0x1, 0x0, 0x1)
	/go/pkg/mod/github.com/hashicorp/go-version@v1.2.0/constraint.go:72 +0x5c
github.com/Praqma/helmsman/internal/app.(*cli).parse(0x17fc460)
	/go/src/github.com/Praqma/helmsman/internal/app/cli.go:155 +0xd75
github.com/Praqma/helmsman/internal/app.init.0()
	/go/src/github.com/Praqma/helmsman/internal/app/main.go:23 +0x2d
```

**Comment by mkubaczyk** [comment]
Everything is fine with helm 3.3.4 as they've changed this https://github.com/helm/helm/commit/e5bd79faefedbbaf4a6a5f7faaa13eba4ddc55aa

**Comment by oxyrox** [comment]
Can confirm that this is working with helm 3.3.4

Thanks @mkubaczyk !

**Comment by mkubaczyk** [comment]
Good, thanks :-)
