### ISSUE TITLE
More detailed docs

### ISSUE THREAD

**Issue by luisdavim** [Praqma/helmsman#52]
Hi, I would like to know more about what are the internal flows of helmsman. Do you have some design docs ?

**Comment by sami-alajrami** [comment]
No docs is available for this right now, the decision making though happens in this file https://github.com/Praqma/helmsman/blob/master/decision_maker.go 

A new version will be coming soon and will have some changes to how the internals work. I will add a document on the internals after these changes. 

Hope this helps.

**Comment by luisdavim** [comment]
thanks for your reply, I'll be looking forward to that new version.
