### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by nvanheuverzwijn** [Praqma/helmsman#523]
@luisdavim Hi, can you make a new release with the latest code commit ? That would be _very_ appreciated!

**Comment by luisdavim** [comment]
Done `v3.4.5` is available in https://github.com/Praqma/helmsman/releases/tag/v3.4.5

**Comment by luisdavim** [comment]
Done `v3.4.5` is available in https://github.com/Praqma/helmsman/releases/tag/v3.4.5
