### ISSUE TITLE
Feature to run other kubernetes commands rather than only helm charts.

### ISSUE THREAD

**Issue by NikoHeikki** [Praqma/helmsman#536]
Hi! 

I don't know if this has been implemented or is something that is out of Helmsman focus/scope but would be nice to also deploy/run other kubectl commands rather than only helm charts. If I want to deploy say for example GoCD/Jenkins and other helm charts, but I like to add own configmaps, secrets, add private docker registry credentials, run script's to create tables to DB for application to work, etc, I have to run those commands manually or make another script to run those. Would be nice to deploy complete namespace full of default/custom helm charts and custom resources. This is very useful when creating set of good applications for customer to use out of the box. Thanks!

**Comment by luisdavim** [comment]
You can use the helmsman hooks to achieve what you describe. Take a look at the docs.

**Comment by luisdavim** [comment]
the changes in https://github.com/Praqma/helmsman/pull/543 will allow you to run any command or script as a hook.

**Comment by NikoHeikki** [comment]
Hi! Okay thanks, didnt notice this, I will look into this @luisdavim

**Comment by luisdavim** [comment]
I think what's currently provided though hooks covers the cases described in this issue.
