### ISSUE TITLE
Add support for helm-secrets

### ISSUE THREAD

**Issue by gorzek** [Praqma/helmsman#54]
Currently, helmsman supports passing secrets via environment variables. It would be helpful to allow secrets in a helmsman configuration through the use of the helm-secrets plugin: https://github.com/futuresimple/helm-secrets

Helmfile (a similar project) offers this capability already: https://github.com/roboll/helmfile

**Comment by rsanders** [comment]
This would be a huge win for our simpler deployments with relatively static secrets, which don't really need other options like AWS Paramstore or Vault.  e.g. TLS secrets for Ingress objects.

**Comment by luisdavim** [comment]
Hi, do you think this would be a simple matter of installing the plugin and running the `helm-wrapper` instead of running `helm` directly?

**Comment by luisdavim** [comment]
This is the implementation from `helmfile` in their solution you have to provide a list of secret files to be decrypted and only then it uses `helm-secrets`, this way they don't have a strong dependency on `helm-secrets`, it's only needed if the user provides secret files.

Just using `helm-wrapper` would be supper easy to implement but it would create a strong dependency on the plugin.

What do you think @rsanders and @sami-alajrami ?

**Comment by rsanders** [comment]
That sounds reasonable to me.

**Comment by luisdavim** [comment]
I'll try to implement this over the weekend.

**Comment by luisdavim** [comment]
@rsanders can you help me test #80 ?
