### ISSUE TITLE
-show-diff missing on chart version bump

### ISSUE THREAD

**Issue by antoinedeschenes** [Praqma/helmsman#555]
Hi @luisdavim, looks like these change prevent the diff from printing when using the -show-diff flag with a chart version bump, as it shortcuts the diff test: https://github.com/Praqma/helmsman/blob/master/internal/app/decision_maker.go#L323

Maybe r.diff() should run in all cases with -show-diff or -verbose mode?

**Comment by luisdavim** [comment]
I'll have a look at this. Thanks for pointing it out.

**Comment by luisdavim** [comment]
@antoinedeschenes I've opened https://github.com/Praqma/helmsman/pull/557 to fix this, can you have a look?
