### ISSUE TITLE
deployment fails with conditional charts 

### ISSUE THREAD

**Issue by tgruenert** [Praqma/helmsman#556]
Type: Bug
working version 2.4.4
version with this bug: 3.6.2

**What i did**
Please see sample desired state specification. In short there are two deployments for the same chart but with different parameter. a group as parameter controls which one has to be deployed.

```
metadata:
  maintainer: "Thomas Grünert"

settings:
  kubeContext: nuwork-dev

namespaces: 
  helmsman-check:
    protected: false

helmRepos:
  stable: "https://charts.helm.sh/stable"
  codecentric: https://codecentric.github.io/helm-charts
  bitnami:  https://charts.bitnami.com/bitnami
  runix: https://helm.runix.net/

appsTemplates:
  
  my-postgres: &my-postgres
    namespace: helmsman-check
    enabled: true
    wait: true
    chart: ./helm-charts/my-postgresql
    version: 0.1.0
    priority: -80
    hooks:
      deleteOnSuccess: true
    
apps:
        
  postgres-stateless:
    <<: *my-postgres
    group: persistence-stateless
    set:
      postgresql.persistence.enabled: false

  postgres-stateful:
    <<: *my-postgres
    group: persistence-stateful
    set:
      postgresql.persistence.enabled: true

```

you can run this example by executing
`helmsman --dry-run --debug --no-banner --no-color --subst-env-values --update-deps -f ./nuworkapp.yaml --group persistence-stateless`

**What i expect**
run a deployment like helmsman version 2.4.4 did.

**What i get**
```
2020-11-25 23:11:30 DEBUG: helm dependency update --skip-refresh \mypath\helm-charts\my-postgresql   
2020-11-25 23:11:30 DEBUG: helm dependency update --skip-refresh \mypath\helm-charts\my-postgresql   
20
2020-11-25 23:11:35 CRITICAL: helm dependency update failed: Error: unable to move current charts to tmp dir: link error: cannot rename \mypath\helm-charts\my-postgresql\charts to \mypath\helm-charts\my-postgresql\tmpcharts: rename \mypath\helm-charts\my-postgresql\charts \mypath\helm-charts\my-postgresql\tmpcharts: Access is denied.
```
at log i can see that helm dependency update is started 2 times. but only one helm chart should be triggerd because of group selector.

**Comment by luisdavim** [comment]
updating deps on both charts seems to be an issue in helmsman but the other one is a permissions issue on your side, you need to run helmsman with a user with permissions do that rename.

**Comment by luisdavim** [comment]
I've added a commit to #557 to address the issue of checking disabled releases.

**Comment by tgruenert** [comment]
@luisdavim 
the command result different error messages depended from your OS.

Result as shown upside is git bash within windows.

Running in Linux gets:
```
2020-11-25 14:16:55 CRITICAL: helm dependency update failed: Error: unable to move current charts to tmp dir: link error: cannot rename /app/helm-charts/nuwork-postgresql/charts to /app/helm-charts/nuwork-postgresql/tmpcharts: rename /app/helm-charts/nuwork-postgresql/charts /app/helm-charts/nuwork-postgresql/tmpcharts: file exists
```

Just for your information.
Greetings and THANK YOU for realy fast response and fix!
Great!

**Comment by luisdavim** [comment]
Can you try this out with a build from master?

**Comment by tgruenert** [comment]
@luisdavim 
i´ve checked this with docker image "latest". Version is shown as 3.4.4.
Deployment works like a charm.
Thank you very much!

**Comment by tgruenert** [comment]
ups. i see that this was running with the old version. i have to check this up again.

**Comment by tgruenert** [comment]
Test with docker praqma/helmsman:latest
reported version v3.6.2
Deployment works like a charm also.
Thank you again and sorry for litte confusion.
Greetings!
