### ISSUE TITLE
Provide multiple sources for hooks

### ISSUE THREAD

**Issue by yenn** [Praqma/helmsman#558]
Hi,

is there a way to somehow provide multiple resources for app hooks? Based on the doc it seems that it is not possible at this point. Is there a way to get around this? In my setup, helmsman is driven by gitops, projecting every git change to various environments. Most of the charts are using overridden image location, to retrieve the images from a private registry (due to docker rate limitation), which means that for most apps (per namespace), I need to setup the secret containing the creds to the registry. If the app requires another manifest to be applied, i am forced to copy the secret to a dedicated file, which creates a lot of unwanted duplicity.

Appreciate your time.

Thank you

JP

**Comment by luisdavim** [comment]
you can place multiple resources into a single file separated by `---` or by using a `List` type.

**Comment by luisdavim** [comment]
the latest version of helmsman also supports running shell commands as hooks, depending on your setup, maybe you can use some script to deal with that...
