### ISSUE TITLE
when adding private repositories fails, passwords can be leaked into the logs

### ISSUE THREAD

**Issue by sami-alajrami** [Praqma/helmsman#561]
When helm add repo fails, the helm error may contain the password of a private repo logged in plain text and Helmsman reports that error back in its logs.

Helmsman v3.4.0 , Helm> v3.3.1
```
CRITICAL: While adding helm repository [myrepo]: Error: looks like "https://user:password@myrepo.jfrog.io/myrepo/myrepo-helm-virtual" is not a valid chart repository or cannot be reached: failed to fetch https://user:password@myrepo.jfrog.io/myrepo/myrepo-helm-virtual/index.yaml : 403 Forbidden
```

Not sure if there is a way to workaround this on the helmsman side.

**Comment by antoinedeschenes** [comment]
Try v3.4.5, I think https://github.com/Praqma/helmsman/pull/505 fixes this as a side-effect
