### ISSUE TITLE
JSON schema

### ISSUE THREAD

**Issue by sacesare** [Praqma/helmsman#576]
Please, provide [json schema](https://www.schemastore.org/) with comments(docs), instead of [desired state specification](https://github.com/Praqma/helmsman/blob/master/docs/desired_state_specification.md )  and some particular tom/yaml cases, for standardized IDE support/documentation.
VScode , for example, can use - [Even Better TOML](https://taplo.tamasfe.dev/configuration/#configuration-file)
Something like [wetzel](https://github.com/CesiumGS/wetzel) can be used to generate md docs from schema if required.
Thanks.

**Comment by luisdavim** [comment]
Hi @sacesare I've opened #675 to add a generated json schema file, can you check if that file fits your use cases?
