### ISSUE TITLE
Parallel Deployments

### ISSUE THREAD

**Issue by mhobotpplnet** [Praqma/helmsman#577]
Our CD consists of deploying apps whatever its in master branch. That said infrastructure looks something like

app1.yaml (valuesfile)
app2.yaml (valuesfile)
deployments.yaml (infrastructure of apps that point to app1/app2)

Now the issue is when we do a deployment, and merge something in master for say app1 we do a plan and deploy is paused. If we merge something else like change to app2 we than get a difference for app1/app2 which is still ok for plan, but we want to deploy those apps individually.

Is there a way to differentiate or pick and chose which app should be deployed regardless of whats in master?

**Comment by mhobotpplnet** [comment]
Lurking bit around the docs, seems like flag target could be the possible answer

**Comment by luisdavim** [comment]
yes, you can use `targets` and `groups` as mentioned in https://github.com/Praqma/helmsman/blob/master/docs/how_to/misc/limit-deployment-to-specific-apps.md and https://github.com/Praqma/helmsman/blob/master/docs/how_to/misc/limit-deployment-to-specific-group-of-apps.md to achieve what you're looking for.
