### ISSUE TITLE
Local paths should be relative to manifest file

### ISSUE THREAD

**Issue by ilyasotkov** [Praqma/helmsman#59]
Having this directory structure
```
.
├── k8s
│   ├── helmsman.yaml
│   └── values
│       └── nginx-ingress.yaml
```
if I run this command from `.` directory
```sh
helmsman -f k8s/helmsman.yaml
```
I need to put this to `helmsman.yaml`:
```yaml
  nginxIngress:
    valuesFile: ./k8s/values/nginx-ingress.yaml
```
but it should be
```yaml
  nginxIngress:
    valuesFile: ./values/nginx-ingress.yaml
```

so that relative paths are consistent regardless of what directory `helmsman` is called from.

**Comment by sami-alajrami** [comment]
this is shipped in v1.5.0. The values file path now should be relative from the (first) desired state file in your Helmsman command. 

If you pass multiple desired state files (new feature in v1.5.0) as follows: 

```
helmsman -f k8s/helmsman1.yaml -f secondDir/helmsman2.yaml   
```
the values files relative path is expected to be relative from the first desired state file. I.e. from `k8s/` 

so in your helmsman1.yaml: 
```
 nginxIngress:
    valuesFile: ./values/nginx-ingress.yaml
``` 

I will close this. But feel free to reopen if the new behaviour does not fix your problem.
