### ISSUE TITLE
Add option to show chart render

### ISSUE THREAD

**Issue by txomon** [Praqma/helmsman#60]
During development, it would be really usefull to see how all the templates have been rendered for debugging purposes. Something similar to `helm template` subcommand would be really helpful.

**Comment by sami-alajrami** [comment]
we could add `dry-run` option to use helm's dry-run option when installing/upgrading releases. That will render your templates and output it. Would that be good?

**Comment by txomon** [comment]
@sami-alajrami anything with the functionality of giving such output is good

**Comment by sami-alajrami** [comment]
The `--dry-run` option is shipped in v1.6.0. I am going to close this issue for now, but feel free to reopen if you are still experiencing issues :)
