### ISSUE TITLE
CI release is failing

### ISSUE THREAD

**Issue by luisdavim** [Praqma/helmsman#604]
The CI release process is failing with:

```
release failed after 110.16s error=github/gitlab/gitea releases: failed to publish artifacts: POST https://api.github.com/repos/Praqma/helmsman/releases: 404 Not Found []
```

@sami-alajrami  can you have a look?

**Comment by luisdavim** [comment]
I think the problem is the API key used in the CI, if @sami-alajrami no longer has access to the Praqma org, can someone from Eficode/Praqma fix this?

**Comment by sami-alajrami** [comment]
@arinzeakubue can you please update that token in CircleCI env variables (its called `GITHUB_TOKEN`). You can replace it with a [github token](https://github.com/settings/tokens/new) that has read/write access to this repo.

**Comment by arinzeakubue** [comment]
@luisdavim @sami-alajrami , the token has been refreshed.

**Comment by arinzeakubue** [comment]
@luisdavim @sami-alajrami , the token has been refreshed.

**Comment by luisdavim** [comment]
Thanks, @arinzeakubue .
Maybe you could give @sami-alajrami contributor access?
