### ISSUE TITLE
Chocolatey package for Helmsman

### ISSUE THREAD

**Issue by veleek** [Praqma/helmsman#632]
I've created a [Chocolatey](https://chocolatey.org/) package to make installing helmsman easier on Windows.  

https://github.com/veleek/chocolatey-packages/tree/main/helmsman

I'd like to package it and make it available on the Chocolatey community repository, but wanted to confirm that sounds reasonable to you.

**Comment by veleek** [comment]
A pre-release version of the package has been published here.  It'll only be visible if you filter in pre-release packages in the search.  I'm planning on releasing a stable version in the next few days.  If you'd like it unlisted for any reason just let me know.

**Comment by luisdavim** [comment]
Sounds good to me, thanks :)

**Comment by veleek** [comment]
https://community.chocolatey.org/packages/helmsman
