### ISSUE TITLE
Helmsman performance using OCI registries

### ISSUE THREAD

**Issue by Revellski** [Praqma/helmsman#639]
Helmsman seems to work considerably slower when using OCI registries. Has anyone else noticed similar issues?

Using ChartMuseum registry a single run averages ~1m45s. Using OCI registry (following [this doc](https://github.com/Praqma/helmsman/blob/4846415ebf12f88894db2401728dbde2014d0edf/docs/how_to/helm_repos/oci.md)) it takes ~4m52s for the same setup (releases, versions & etc).

Tweaking the concurrency using `-p int` from 1 to 15 (considering there are 15 charts) improves the run to 4m7s but is still over x2 slower than using ChartMuseum registries.

Could there be additional configuration I am missing which could improve performance? Perhaps define the OCI registries in `helmRepos` stanza? 

```
Helmsman v3.8.0
Helm v3.7.2
Helm Diff v3.1.3
Kubectl v1.20.5
```

_Update (2022/02/04):_
The debug logs reveal `helm pull oci://` is the slowest out of all operations. Unfortunately, it does not respect the concurrency settings passed by the `-p {int}` parameter but appears to be synchronous.

**Comment by luisdavim** [comment]
We can look into adding parallelization to that step, but I'm not sure if helm will allow it.

**Comment by luisdavim** [comment]
I'm closing this as I'm pretty sure this is no longer an issue with newer versions of `hlem` and `helmsman` feel free to re-open if you find it's still an issue.
