### ISSUE TITLE
Env variable substitution : .bashrc/current session env takes precedence over supplied .env file

### ISSUE THREAD

**Issue by claireleray-poclain** [Praqma/helmsman#645]
Hi!

It seems that when applying a configuration using a command looking like  `helmsman --apply --subst-env-values -e <config-file.env>  -f helmsman.yaml`, Helmsman first uses variables from .bashrc instead of the supplied config file. Is that the expected behavior ? If so, could that maybe made clearer in the documentation ?

Thanks!

**Comment by luisdavim** [comment]
I'm not sure if I get what you are reporting. 

Any process that you start will "see" the variables that are already set in your session, for example, the ones from `bashrc`.

In this case, helmsman will read the env file you provided and load them on top of the ones that already existed before, so the variables set on the env file should take precedence. If the same variable is set both on your `bashrc` file and in the env file you provided, helmsman should end up using the value set on the env file.

Are you saying that if a variable is set on both, helmsman is ignoring the value from the env file and using the one from `bashrc`? That should not happen and if it does it's a bug.

**Comment by claireleray-poclain** [comment]
Yes ! Variables were set on both, and I had to strip my `bashrc` so that Helmsman would use the ones in my env file.

**Comment by luisdavim** [comment]
Ok, that should not happen. I'll have a look.

**Comment by luisdavim** [comment]
This is fixed in #649 I'll cut a release soon.
