### ISSUE TITLE
Is there a way to make helmsman not look for charts/files for the services which are disabled 

### ISSUE THREAD

**Issue by varunvijayagopal** [Praqma/helmsman#684]
[apps.docmosis]
    priority = -820
    name = "docmosis"
    namespace = "$namespace"
    enabled = $docmosis_enabled
    chart = "oci://$acr_url/charts/docmosis"
    version = "0.1.1"
    valuesFiles = [
      "./ansible/group_vars/$environment/docmosis_values.yml",
      "./ansible/group_vars/$environment/$stack/docmosis_values.yml",
    ]
    wait = $wait_for_service_to_be_up

We are using
 enabled = $docmosis_enabled to identify a service has to be deployed to an environment or not .
Irrespective of whether it is enabled or not , helmsman tries to pull or validate the charts , and it fails as the chart won't be present in live as this is needed only for nonlive.

Also helmsman look for the valuesfiles even if the service is disabled . IS there a way to look for chart or values files only for the services which are enabled

**Comment by mkubaczyk** [comment]
It sounds like something worth being added. Let me find it out. I'll get back to you to see if that's something easy to do.

**Comment by mkubaczyk** [comment]
Making the code ignore disabled apps when it comes to pulling and validating charts is doable, but I don't think the same applies to loading values. The code resolves absolute paths way earlier before validation of DSF happens so if we'd like to skip disabled apps, we'd have to exclude them from the overall DSF validation which I don't think is a good thing. We always want the DSF to be valid no matter what. 
In such case when app is validated only when being enabled, you'd miss plenty of situations with new apps being pushed to DSF which will only come up when enabling then.
