### ISSUE TITLE
Folder .helmsman-tmp is not deleted

### ISSUE THREAD

**Issue by claireleray-poclain** [Praqma/helmsman#692]
Hi,

I recently upgraded to Helmsman v3.12.0. Since then, when I apply my charts, the .helmsman-tmp folder is not deleted after the execution, even though there's no visible error. Has something changed in this folder's behavior ?

Thanks :)
Claire

**Comment by mkubaczyk** [comment]
Hey,

thanks for reporting that. There's such problem indeed. I tracked the change that caused that, which is #668, os.Exit does not respect defer that should be running the cleanup. I'll fix that.

**Comment by claireleray-poclain** [comment]
Amazing, thanks a lot!
