### ISSUE TITLE
App Forward Versioning

### ISSUE THREAD

**Issue by Tech-S1** [Praqma/helmsman#712]
Currently you have to explicitly set the version in the desired state files.

I have an environment that gets deployed via helmsman from a helm repo. I wondered if there were any ways to ensure in the development environment it uses the latest version in the helm repo rather than manually updating these versions?

If there's no easy was is there a reason there no support for forward versioning?

**Comment by luisdavim** [comment]
Hi @Tech-S1 I've creted #735 to address this, can you try a build from that branch and set the chart version to `latest`?

**Comment by AndyBurdett** [comment]
This fix doesn't work

**Comment by AndyBurdett** [comment]
It fails on line 59 of helmsman/internal/app/helm_helpers.go
if the chartVersion is latest the constraint fails.
the constraint check needs to be ignore when chartVersion is latest.
