### ISSUE TITLE
Trigger new release?

### ISSUE THREAD

**Issue by amadeusjposchmann** [Praqma/helmsman#727]
#723 has been merged for a while, but no new release has been cut since. What has to be done to trigger a new release? Judging by CONTRIBUTING.md, you'd need push access to the master branch to cut a new release.

**Comment by mkubaczyk** [comment]
Release can be created only if you're the reviewer of the repo. I guess it took so long because we expected #713 to be finished soon so it can be included but it's stale so I cut the v3.15.1, it's on its way.
