### ISSUE TITLE
Regression with helm-secrets plugin v4.2.2 interaction broken, v4.2.1 works fine.

### ISSUE THREAD

**Issue by zied-jt** [Praqma/helmsman#737]
Hello here,

[helm-secrets release v4.2.2](https://github.com/jkroepke/helm-secrets/releases/tag/v4.2.2) broke interaction that was fixed in #723. The same behavior as #715 is produced

```bash
output: 
--- stdout ---

--- stderr ---
Error: unknown command "dec" for "helm"

Did you mean this?
	get

Run 'helm --help' for usage.
Error: plugin "secrets" exited with error
```

As a workaround, freeze helm-secrets to `v4.2.1`

**Comment by luisdavim** [comment]
so in `v4.2.2` `helm-secrets` when back to the previous command format?

**Comment by luisdavim** [comment]
I've had a quick look at the code and if you're using any version of `helm-secrets` greater than `v4.0.0` `helmsman` will not use `dec` but it will use `decrypt` instead, can you share what versions of `helm`; `helmsman` and `helm-secrets` you're using?

**Comment by zied-jt** [comment]
@luisdavim, I read the code and I think that I find the issue:
- `helm-secret` new version is released as `4.2.2-dev` instead of `4.2.2`
- In `helmsman` source code, the semver behavior in [this line](https://github.com/Praqma/helmsman/blob/c1479287b11f787a6d90d4a272346cb915a1a559/internal/app/utils.go#L479) occording to the  [Semver doc ](https://github.com/Masterminds/semver) will not consider `helm-secret` version `4.2.2-dev`: 
> SemVer comparisons using constraints without a prerelease comparator will skip prerelease versions. For example, >=1.2.3 will skip prereleases when looking at a list of releases while >=1.2.3-0 will evaluate and find prereleases.

We could either include pre-release version in `helmsman` behavior or raise un issue in `helm-secret` side (or both ?)

```patch
- useHelmOutput := checkHelmPlugVersion("secrets", ">=4.0.0") || settings.EyamlEnabled
+ useHelmOutput := checkHelmPlugVersion("secrets", ">=4.0.0-0") || settings.EyamlEnabled
```

**Comment by zied-jt** [comment]
Thats said here is another workaroud if `v4.2.2` is needed:

- download the plugin tar and extract it
- edit the `plugin.yaml` and replace `4.2.2-dev` by `4.2.2`
```yaml
# plugin.yaml
name: "secrets"
version: "4.2.2"
…
```
- uninstall old version: `helm plugin uninstall secrets`
- install the new version: `SKIP_SOPS_INSTALL=true helm plugin install <MODIFIED-PLUGIN-DIR>`

**Comment by luisdavim** [comment]
I can add the pre-release suffix

**Comment by luisdavim** [comment]
> I can add the pre-release suffix

I've updated https://github.com/Praqma/helmsman/pull/738 to include it.
