### ISSUE TITLE
Pipeline credentials

### ISSUE THREAD

**Issue by luisdavim** [Praqma/helmsman#761]
Looks like it is no longer possible to create releases as the credentials stored in CircleCI seem to have expired:

https://app.circleci.com/pipelines/github/Praqma/helmsman/866/workflows/2e0fb140-2929-4c3a-a9dd-487929b1e8fc/jobs/2683

**Comment by mkubaczyk** [comment]
I regenerated the token, CI should work now

**Comment by luisdavim** [comment]
seems to be working now, thanks.
