### ISSUE TITLE
Support for `helm pull` and/or `helm template` for configured templates

### ISSUE THREAD

**Issue by tillig** [Praqma/helmsman#768]
For auditing/archival/reporting sorts of functions, it's interesting to have the ability to:

- Download all the Helm charts you're using to deploy a system (`helm pull`).
- Execute a `helm template` given your TOML file + values files and dump all the YAML to a file that would otherwise get deployed in a "clean install."

It would be nice to be able to do something like:

```sh
# Download all charts to a location
helmsman -f cluster.toml -pull -o ~/Downloads/charts

# Template everything that would normally get deployed in a fresh install
helmsman -f cluster.toml -template > full-deploy.yaml
```

For a moment I thought the `-download-charts` flag did `-pull` but it doesn't; I misunderstood the flag.

**Comment by mkubaczyk** [comment]
regarding templating: `--dry-run` prints out templated chart, you can use it together with `--always-upgrade` to make Helmsman dry-run everything instead of looking for diff first. Would this cover your need?

regarding download I don't think we have solution atm.

**Comment by tillig** [comment]
Not stale.
