### ISSUE TITLE
helmsman does not escape values used in helm command lines

### ISSUE THREAD

**Issue by rsanders** [Praqma/helmsman#78]
I tried to use a chart version constraint of `~0` and helm failed to find chart 0.2.5.  Doing a search from my shell worked.  Long story short, it turns out that bash is expanding `~0` because helmsman doesn't escape or quote the '~'.

My DSF fragment that failed:

```
  [apps.zz-testchart]
    name = "zz-testchart"
    description = "local repo test chart"
    namespace = "examples"
    enabled = true
    chart = "myrepo/zz-testchart"
    version = "~0"
```

This is the offending code (though similar code exists elsewhere in the app): https://github.com/Praqma/helmsman/blob/v1.5.0/helm_helpers.go#L206

I can't tell whether this is intentional (e.g. to allow use of env vars in these parameters) or an oversight. 

This is also a security issue in that a user-supplied parameter in the DSF can execute arbitrary commands.  e.g. `version = "; rm -rf /"`.  Of course, any working helmsman install is fairly powerful in its own right; and any edits to the DSF can execute arbitrary pods. But it might be used to exfiltrate cluster admin credentials from the helmsman pod.

If env var expansion is wanted, `os.ExpandEnv` applied deliberately would be much better.

**Comment by rsanders** [comment]
Meant to say - I'd be happy to work on this, but wanted to know whether there are features of the `bash -c` approach that are desired. e.g. env var expansion

**Comment by luisdavim** [comment]
I think that simply adding `'` around `r.Chart` should do it, env variable expansion is already covered whilst reading the state files in `state.go` `func subsituteEnv(name string) string `

**Comment by luisdavim** [comment]
wasn't this fixed with #95 ? @rsanders can you confirm?

**Comment by kleetus** [comment]
I think this is resolved now. At least as far as I can tell.

**Comment by rsanders** [comment]
There's still vulnerability to deliberate and accidental shell command parsing hijinks, but my use case (server version constraints) was addressed with the recent patches.
