### ISSUE TITLE
Possible to cut a new release ?

### ISSUE THREAD

**Issue by 1fox1** [Praqma/helmsman#82]
Hi,

Would it be possible to cut a new release after the recent PR merges from Luis.

Many thanks,

Matt

**Comment by sami-alajrami** [comment]
Done. v1.6.0 is released. You can use the [binaries](https://github.com/Praqma/helmsman/releases) and the [docker images](https://hub.docker.com/r/praqma/helmsman/tags/)

**Comment by 1fox1** [comment]
thanks, just a note the install section still has 1.5.0 in the readme

**Comment by sami-alajrami** [comment]
fixed! thanks :)
