### ISSUE TITLE
upgrade determination fails with versions containing '-'

### ISSUE THREAD

**Issue by rsanders** [Praqma/helmsman#85]
We have some charts which are always flagged as needing an upgrade, even though neither the DSF nor the charts available in our Helm repo have changed.

For example, this happens every time we run Helmsman, no matter what:

    DECISION: release [ elasticsearch ] is desired to be upgraded. Planing this for you! -- priority: 0

Upon examination, we discovered that all of them had versions specified in the DSF that were not simple  X.Y.Z version strings.

There are two cases in which this happens:

1.  The DSF contains valid semver versions which include pre-release info after a '-' character.  e.g. `version = "1.3.0-1"`. The reason this breaks is that helmsman splits the string returned by `helm list` on the last `-` character to split it into chart name and version.  It's unfortunate that helm shows the version of elasticsearch as a single string `elasticsearch-1.3.0-1` and so this sort of string butchery is required.

2. We included a version constraint in the helmsman DSF rather than a literal version. Helmsman doesn't resolve that into the version that it would generate before doing the comparison.  e.g. `version = "'>=0.1.3'"`

**Comment by sami-alajrami** [comment]
@luisdavim there are 2 places string is split by `-` 
https://github.com/Praqma/helmsman/blob/fdfd09267d02173d1bcd99d5f4733947eff6416d/helm_helpers.go#L177
https://github.com/Praqma/helmsman/blob/fdfd09267d02173d1bcd99d5f4733947eff6416d/helm_helpers.go#L185
