### ISSUE TITLE
helmsman 1.6.0 appears to require helm 2.10.0

### ISSUE THREAD

**Issue by rsanders** [Praqma/helmsman#87]
There is some issue with helm-diff and the `--tiller-namespace` argument that seem to require that helm 2.10.0 be used.  Otherwise the `helm diff` run throws errors.

See https://github.com/databus23/helm-diff/pull/44 and https://github.com/helm/helm/pull/3944.

**Comment by luisdavim** [comment]
I see that you have a branch with a fix https://github.com/Cybraics/helmsman/tree/feature/helmdiff-namespace-fix are you going to open a PR?

**Comment by rsanders** [comment]
@luisdavim it didn't actually appear to help in my first test. I'll take another look. If not that, then setting TILLER_NAMESPACE env var rather than passing the cmd line arg would probably work.

**Comment by rsanders** [comment]
I could probably address this and #78 with one PR to change the invocation framework a bit. Might be Monday before I could get to it.
