### ISSUE TITLE
helmsman --destroy

### ISSUE THREAD

**Issue by afoninsky** [Praqma/helmsman#88]
**Feature request**: ability to delete infrastructure described in file.
Use case: possibility to use this command in CI/CD automatic integration tests
```
step1: bootstrap test environment
step2: perform integration tests
step3: remove test environment
```

**Additional feature request**: ability to add prefix or postfix to helm names via command line (so we can reuse one infrastructure file in various tests

**Comment by sami-alajrami** [comment]
@afoninsky for the destroy option, I think it makes sense to delete only resources created by helmsman (currently the helm releases). Until better management is implemented for created namespaces/contexts etc. Would that work for you?

For the second feature, could the existing `--ns-override` work for you (overrides all releases namespaces with the one passed from command line) ?

**Comment by afoninsky** [comment]
Sure, it would be good. Thank you.
ns overrides sounds good

**Comment by sami-alajrami** [comment]
@afoninsky the `--destroy` option is added in #90 . 
Please note, that the deletion of releases will respect the `purge` flag in the desired state file. i.e. only if purge is true for release A, then the destruction of A will be a purge delete.
