### ISSUE TITLE
Global overwrite of values for all apps?

### ISSUE THREAD

**Issue by patrickjane** [Praqma/helmsman#885]
Is it possible to do something like `helmsman --apply -f example.toml --set myvar=myval` to set a number of values, overwriting values.yaml of ALL apps in the TOML file?

I need to have a helmsman file containing all my microservices of my application, but with the possibility to select a configuration-version for all microservice upon deploy, since this is not part of the software version.

**Comment by luisdavim** [comment]
I don't think that's currently supported but it shouldn't be too hard to add.
