### ISSUE TITLE
make build is failing

### ISSUE THREAD

**Issue by luisdavim** [Praqma/helmsman#91]
Hi,

I pulled the latest code and got this when running `make build`:
```
$ make build
# _/Users/ldavim/workingCopies/code/github/PTC-Global/helmsman
./utils.go:181:15: too many arguments in call to aws.ReadFile
        have (string, string, string, bool)
        want (string, string, string)
./utils.go:186:15: too many arguments in call to gcs.ReadFile
        have (string, string, string, bool)
        want (string, string, string)
make: *** [build] Error 2
```

**Comment by luisdavim** [comment]
it worked after I removed some of the cached dependencies from `~/go/src/` maybe we should start using something like https://golang.github.io/dep/docs/introduction.html to manage dependencies and their versions.

**Comment by luisdavim** [comment]
https://github.com/blindpirate/report-of-build-tools-for-java-and-golang#golang

**Comment by sami-alajrami** [comment]
@luisdavim I have added the dep files. 
As those two packages in the above issue are internal, changes to them will have to be pushed to github first before `dep ensure` can get the updated dependencies.

**Comment by luisdavim** [comment]
we should update the makefile to use godep instead of fetching all the libs.

**Comment by luisdavim** [comment]
https://github.com/Clever/dev-handbook/blob/master/golang/dep.md

**Comment by luisdavim** [comment]
I can open a PR for that if you want.

**Comment by luisdavim** [comment]
ok, introducing `dep` forces people that want to contribute to this project to clone it into a `GOPATH/src` directory, I can workaround it in the make file and keep things as they where without `dep` and anyone can clone this repo into any path and all `make` commands will just work, that will had some complexity to the `Makefile`.
If you don't think that's important, we can keep the make file simple and contributors will have to abide to the `GOPATH`.
I can open a `WIP` PR with the "complex" version for you to see what I mean....
