### ISSUE TITLE
Helmsman fails to add Helm repos URLs containing special characters

### ISSUE THREAD

**Issue by epierotto** [Praqma/helmsman#94]
Helm repos URL are not quoted when added by Helmsman causing the following error when the URL contains special characters:
```bash
ERROR: chart foo-repo/foo-app-0.1.2 is specified for app [foo-app] but is not found in the defined repos
```

The repo can be added manually quoting the URL `helm repo add foo-repo "URL"`

**Comment by sami-alajrami** [comment]
If it reaches the stage of checking charts exists or not, then it must have done the repo add without facing errors. It's only possible to debug it if you share more information :)

**Comment by epierotto** [comment]
If you try to add the following repo with helm you can see the errors :

Without quotes:
```
helm repo add test-incubator https://testhelmrepos.blob.core.windows.net/incubator/?se=2018-12-10&sp=rl&sv=2015-08-29&sr=c&sig=91mfyYXpS5eDEh8SdVc4Q6laYeYby2sPACQ5vnY%2BzH8%3D
[1] 98447
[2] 98448
[3] 98449
[4] 98450
[2]   Done                    sp=rl
[3]-  Done                    sv=2015-08-29
[4]+  Done                    sr=c
```

With quotes (Please ignore the error "not a valid chart repository", the URL is just an example and is an invalid repo):
```
helm repo add test-incubator "https://testhelmrepos.blob.core.windows.net/incubator/?se=2018-12-10&sp=rl&sv=2015-08-29&sr=c&sig=91mfyYXpS5eDEh8SdVc4Q6laYeYby2sPACQ5vnY%2BzH8%3D"
Error: Looks like "https://testhelmrepos.blob.core.windows.net/incubator/?se=2018-12-10&sp=rl&sv=2015-08-29&sr=c&sig=91mfyYXpS5eDEh8SdVc4Q6laYeYby2sPACQ5vnY%2BzH8%3D" is not a valid chart repository or cannot be reached: Get https://testhelmrepos.blob.core.windows.net/incubator/index.yaml?se=2018-12-10&sp=rl&sv=2015-08-29&sr=c&sig=91mfyYXpS5eDEh8SdVc4Q6laYeYby2sPACQ5vnY%2BzH8%3D: dial tcp: lookup testhelmrepos.blob.core.windows.net on 10.152.224.74:53: no such host
```

**Comment by epierotto** [comment]
Using quotes around the Helm repo URL solves the issue, I've tested it and submitted a PR.

**Comment by sami-alajrami** [comment]
thanks @epierotto .. your PR fixes the quoting issue. But this problem highlights another one: the helm repo add command failure does not get caught (even with the broken link you posted). But that's another issue to fix.
